### PR TITLE
Add #:lib-suffix parameter to ffi-lib call.

### PR DESCRIPTION
**Pull request by LeifAndersen**
This is useful if you have a library that doesn't use the usual extension (namely so on os x).

Still need to add docs.

### CODE REVIEW

**Comment by mflatt** [comment]
`ffi-lib` tries the path that you provide without adding any suffix. For your case, can you just include the suffix in the `ffi-lib` path argument?

**Comment by LeifAndersen** [comment]
Oh, interesting. That's not what the docs say:

> path is a path without a version or suffix (i.e., without ".dll", ".so", or ".dylib"); and

Should I update them to say that the path _can_ potentially include the suffix?

**Comment by mflatt** [comment]
That bit of documentation is after "Normally", and there are several constraints in that itemization that aren't always true, as detailed in the rest. The rest is long and complex, which is why there's a "Normally" to explain the typical use. Maybe you can see a rewrite to make the "Normally" aspect more clear.

**Comment by LeifAndersen** [comment]
Oh hey...I completely missed that. Thanks. :)

**Pull request closed without merging**
