### PR TITLE
Run workflow directly in VM

### PR DESCRIPTION
**Pull request by pmatos**
Related to #3730

### CODE REVIEW

**Comment by pmatos** [comment]
Interested in seeing if this solves the issues we are seeing or if it's really a problem in the tests introduced since the test started failing March 10.

**Comment by pmatos** [comment]
There are some actual issues in 32 bits although running the tests directly on the vm does fix the containerization issues.
@mflatt any ideas what's going on with these failures (unique to 32bits): https://github.com/racket/racket/runs/2121096966?check_suite_focus=true#step:10:199 ?

**Comment by mflatt** [comment]
Looking into the first one, I do see a real bug with cp0 enabled:
```
> (time=?  (make-time 'time-duration 989666791 -2) #f)
#<time-duration -1.010333209>
```
I will investigate more.

**Comment by mflatt** [comment]
The problem there is a bad spec of `make-time` in "primdata.ss". It claims that the nanosecond part is always a fixnum, but that's not true on a 32-bit platform.

**Comment by mflatt** [comment]
It looks like all the failures may be the same problem. I've pushed a repair as a5db4bf376771baac66fbb98d63574387914fe94.

**Comment by gus-massa** [comment]
Should this be fixed too?


https://github.com/racket/racket/blob/a5db4bf376771baac66fbb98d63574387914fe94/racket/src/ChezScheme/s/primdata.ss#L863

**Comment by mflatt** [comment]
Yes - thanks!

**Comment by pmatos** [comment]
Rerunning the tests on rebased branch - thanks for the fix.

**Comment by pmatos** [comment]
@mflatt the date issue seems to be affecting 64bits now. https://github.com/racket/racket/pull/3731/checks?check_run_id=2122559726#step:10:198

**Comment by gus-massa** [comment]
I fixed the test in 64 bits, but now there are a lot of (unrelated) errors about files. For example:

https://github.com/racket/racket/runs/2143976239?check_suite_focus=true#step:11:262

    > 6.mo:Bug in mat filesystem-operations clause 81 at line 2947, char 3 of 6.ms
    > 6.mo:Bug in mat filesystem-operations clause 82 at line 2948, char 3 of 6.ms

https://github.com/racket/racket/blob/993b86ffa364ca5f1080d9fa3ec4cf1d61abbe8b/racket/src/ChezScheme/mats/6.ms#L2947-L2948

**Comment by xxyzz** [comment]
> but now there are a lot of (unrelated) errors about files.

That might be caused by the container. If this pr get rebased again, all tests should pass.

**Comment by pmatos** [comment]
> I fixed the test in 64 bits, but now there are a lot of (unrelated) errors about files. For example:
> 
> https://github.com/racket/racket/runs/2143976239?check_suite_focus=true#step:11:262
> 
> ```
> > 6.mo:Bug in mat filesystem-operations clause 81 at line 2947, char 3 of 6.ms
> > 6.mo:Bug in mat filesystem-operations clause 82 at line 2948, char 3 of 6.ms
> ```
> 
> https://github.com/racket/racket/blob/993b86ffa364ca5f1080d9fa3ec4cf1d61abbe8b/racket/src/ChezScheme/mats/6.ms#L2947-L2948

Really unsure why this is happening atm. Thanks for the fix.

**Comment by pmatos** [comment]
> > but now there are a lot of (unrelated) errors about files.
> 
> That might be caused by the container. If this pr get rebased again, all tests should pass.

Ah - after reading your comment, I see why the tests are failing.

**Comment by pmatos** [comment]
I have now rebased my PR.

**Comment by pmatos** [comment]
This looks good now. Thanks all.

**Pull request merged**
