### PR TITLE
add :do-in fast path for in-hash

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

**Comment by stchang** [comment]
Here are some microbenchmarks

Before:
```
slow first, fast second
immutable --------------------
in-hash
cpu time: 4900 real time: 4912 gc time: 0
cpu time: 4909 real time: 4920 gc time: 0
in-hash-pairs
cpu time: 4904 real time: 4916 gc time: 4
cpu time: 4900 real time: 4911 gc time: 0
in-hash-keys
cpu time: 2676 real time: 2684 gc time: 0
cpu time: 2729 real time: 2734 gc time: 0
in-hash-values
cpu time: 2664 real time: 2674 gc time: 0
cpu time: 2672 real time: 2675 gc time: 0
mutable --------------------
in-hash
cpu time: 720 real time: 725 gc time: 0
cpu time: 724 real time: 725 gc time: 0
in-hash-pairs
cpu time: 708 real time: 709 gc time: 0
cpu time: 704 real time: 707 gc time: 4
in-hash-keys
cpu time: 528 real time: 529 gc time: 0
cpu time: 560 real time: 562 gc time: 0
in-hash-values
cpu time: 524 real time: 522 gc time: 0
cpu time: 520 real time: 525 gc time: 0
weak --------------------
in-hash
cpu time: 1628 real time: 1629 gc time: 0
cpu time: 1628 real time: 1633 gc time: 0
in-hash-pairs
cpu time: 1617 real time: 1621 gc time: 0
cpu time: 1644 real time: 1648 gc time: 0
in-hash-keys
cpu time: 1472 real time: 1478 gc time: 0
cpu time: 1504 real time: 1507 gc time: 0
in-hash-values
cpu time: 1232 real time: 1233 gc time: 0
cpu time: 1216 real time: 1222 gc time: 0
```

After:
```
slow first, fast second
immutable --------------------
in-hash
cpu time: 4056 real time: 4066 gc time: 0
cpu time: 3900 real time: 3910 gc time: 0
in-hash-pairs
cpu time: 4012 real time: 4025 gc time: 0
cpu time: 3925 real time: 3933 gc time: 0
in-hash-keys
cpu time: 2276 real time: 2284 gc time: 0
cpu time: 2008 real time: 2014 gc time: 0
in-hash-values
cpu time: 2332 real time: 2341 gc time: 0
cpu time: 2072 real time: 2076 gc time: 0
mutable --------------------
in-hash
cpu time: 772 real time: 775 gc time: 0
cpu time: 460 real time: 459 gc time: 0
in-hash-pairs
cpu time: 684 real time: 688 gc time: 0
cpu time: 436 real time: 435 gc time: 0
in-hash-keys
cpu time: 572 real time: 574 gc time: 0
cpu time: 308 real time: 309 gc time: 0
in-hash-values
cpu time: 548 real time: 548 gc time: 0
cpu time: 281 real time: 282 gc time: 0
weak --------------------
in-hash
cpu time: 1780 real time: 1784 gc time: 0
cpu time: 1396 real time: 1400 gc time: 0
in-hash-pairs
cpu time: 1804 real time: 1811 gc time: 4
cpu time: 1352 real time: 1353 gc time: 0
in-hash-keys
cpu time: 1616 real time: 1623 gc time: 0
cpu time: 984 real time: 985 gc time: 0
in-hash-values
cpu time: 1096 real time: 1097 gc time: 0
cpu time: 824 real time: 826 gc time: 0
```

**Comment by stchang** [comment]
Here's the test file:

```
#lang racket
(define big-list (build-list 10000000 add1))

(define big-hash/immut (make-immutable-hash (map cons big-list big-list)))
(define big-hash/mut (make-hash (map cons big-list big-list)))
(define big-hash/weak (make-weak-hash (map cons big-list big-list)))

(define big-hash/immut/seq (in-hash big-hash/immut))
(define big-hash/mut/seq (in-hash big-hash/mut))
(define big-hash/weak/seq (in-hash big-hash/weak))

(define big-hash/immut-pairs/seq (in-hash-pairs big-hash/immut))
(define big-hash/mut-pairs/seq (in-hash-pairs big-hash/mut))
(define big-hash/weak-pairs/seq (in-hash-pairs big-hash/weak))

(define big-hash/immut-keys/seq (in-hash-keys big-hash/immut))
(define big-hash/mut-keys/seq (in-hash-keys big-hash/mut))
(define big-hash/weak-keys/seq (in-hash-keys big-hash/weak))

(define big-hash/immut-vals/seq (in-hash-values big-hash/immut))
(define big-hash/mut-vals/seq (in-hash-values big-hash/mut))
(define big-hash/weak-vals/seq (in-hash-values big-hash/weak))

(collect-garbage)
(collect-garbage)
(collect-garbage)

(displayln "slow first, fast second")
(require rackunit)

(displayln "immutable --------------------")
(displayln "in-hash")
(check-equal?
  (time (for/sum ([(k v) big-hash/immut/seq]) k))
  (time (for/sum ([(k v) (in-hash big-hash/immut)]) k)))
(displayln "in-hash-pairs")
(check-equal?
  (time (for/sum ([k+v big-hash/immut-pairs/seq]) (car k+v)))
  (time (for/sum ([k+v (in-hash-pairs big-hash/immut)]) (car k+v))))
(displayln "in-hash-keys")
(check-equal?
  (time (for/sum ([k big-hash/immut-keys/seq]) k))
  (time (for/sum ([k (in-hash-keys big-hash/immut)]) k)))
(displayln "in-hash-values")
(check-equal?
  (time (for/sum ([v big-hash/immut-vals/seq]) v))
  (time (for/sum ([v (in-hash-values big-hash/immut)]) v)))

(displayln "mutable --------------------")
(displayln "in-hash")
(check-equal?
  (time (for/sum ([(k v) big-hash/mut/seq]) k))
  (time (for/sum ([(k v) (in-hash big-hash/mut)]) k)))
(displayln "in-hash-pairs")
(check-equal?
  (time (for/sum ([k+v big-hash/mut-pairs/seq]) (car k+v)))
  (time (for/sum ([k+v (in-hash-pairs big-hash/mut)]) (car k+v))))
(displayln "in-hash-keys")
(check-equal?
  (time (for/sum ([k big-hash/mut-keys/seq]) k))
  (time (for/sum ([k (in-hash-keys big-hash/mut)]) k)))
(displayln "in-hash-values")
(check-equal?
  (time (for/sum ([v big-hash/mut-vals/seq]) v))
  (time (for/sum ([v (in-hash-values big-hash/mut)]) v)))

(displayln "weak --------------------")
(displayln "in-hash")
(check-equal?
  (time (for/sum ([(k v) big-hash/weak/seq]) k))
  (time (for/sum ([(k v) (in-hash big-hash/weak)]) k)))
(displayln "in-hash-pairs")
(check-equal?
  (time (for/sum ([k+v big-hash/weak-pairs/seq]) (car k+v)))
  (time (for/sum ([k+v (in-hash-pairs big-hash/weak)]) (car k+v))))
(displayln "in-hash-keys")
(check-equal?
  (time (for/sum ([k big-hash/weak-keys/seq]) k))
  (time (for/sum ([k (in-hash-keys big-hash/weak)]) k)))
(displayln "in-hash-values")
(check-equal?
  (time (for/sum ([v big-hash/weak-vals/seq]) v))
  (time (for/sum ([v (in-hash-values big-hash/weak)]) v)))
```

**Comment by gus-massa** [comment]
Slightly offtopic: It's very strange that the immutable version is much slower than the mutable version. (Moreover, I expected a small overhead in the mutable version, for example to ensure that the operations are thread safe.) Do anyone know the reason?

**Comment by stchang** [comment]
> immutable version is much slower than the mutable version

They have different representations. Immutable hashes are trees, so are slower to iterate. Mutable hashes appear to use arrays, so iteration is faster but access is probably slower for hash collisions.

**Pull request merged**
