### PR TITLE
Chez Scheme: add missing type in primvars.ms

### PR DESCRIPTION
**Pull request by gus-massa**
The definition of `*pseudo-random-generator` was missing and it created spurious errors.

I don't know how to build the new version of the files with the expected errors.

### CODE REVIEW

**Comment by gus-massa** [comment]
Probably 

  cd ChezScheme/ta6le/mats/
  zuo . test-experr
  zuo . experr

?

I get this error:

```
Computer:~/Desktop/racket/racket/src/ChezScheme/ta6le/mats$ ../../../build/bin/zuo . test-experr
patch experr-interpret-0-f-f-f ../../mats/patch-interpret-0-f-f-f
patching file experr-interpret-0-f-f-f
Hunk #1 FAILED at 24.
Hunk #2 FAILED at 83.
Hunk #3 FAILED at 110.
Hunk #4 FAILED at 273.
Hunk #5 FAILED at 654.
Hunk #6 FAILED at 7691.
Hunk #7 FAILED at 8086.
Hunk #8 FAILED at 8130.
Hunk #9 FAILED at 9412.
Hunk #10 FAILED at 10198.
Hunk #11 FAILED at 10229.
Hunk #12 FAILED at 10262.
Hunk #13 FAILED at 10293.
Hunk #14 FAILED at 10936.
14 out of 14 hunks FAILED -- saving rejects to file experr-interpret-0-f-f-f.rej
shell command failed
 in build-one
 in target experr-interpret-0-f-f-f
 in target interpret-0-f-f-f-experr
 in target test-experr
 in do-build
 in foldl
 in build-unbuilt {2}
 in target interpret-0-f-f-f-experr
 in target test-experr
 in do-build
 in foldl
 in build-unbuilt {2}
 in target test-experr
 in do-build
 in loop
 in module->hash
```

**Comment by mflatt** [comment]
That's the right sequence. You were definitely starting with the original `root-` and `patch-` files? I'm not sure why the patch would fail, but I'll try updating with this commit later today.

**Comment by mflatt** [comment]
I added the patch-file changes (to your branch) that I get from `zuo . test-experr` and `zuo . experr`. Do these work right when you build and test?

**Comment by gus-massa** [comment]
I fixed my problem using `./configure` or switching to another branch and back, I'm not sure.
  
So before you posted your commit, I ran `zuo . test-experr ` overnight but I got some weird errors in `root-experr-compile-3-f-f-f`.  Many lines like: 

    +examples.mo:Error in mat def-edit clause 1: 
        "incompatible fasl-object version 9.9.9-pre-release.14 found in 
         /home/gus/Desktop/racket/racket/src/ChezScheme/ta6le/examples/def.so"

So I deleted those files and ran `zuo . test-experr ` and tried again, and got a different set weird errors. I'll try again another day to understand the problem.

---

Your `experr` files fix the problem in GitHub. Do I squash both commit and push the result to master or do you prefer that I keep them as different commits?

**Comment by mflatt** [comment]
I prefer squashing the commit into yours — thanks!

**Comment by gus-massa** [comment]
Merged in https://github.com/racket/racket/commit/e39f8344c0592229013cf6168bae922d717eee81

**Pull request closed without merging**
