### PR TITLE
Initial commit to new CI system based on GitHub Actions

### PR DESCRIPTION
**Pull request by pmatos**
Jobs to build CGC, 3m and CS separately on Linux.
macOS is failing during CGC install - need to investigate.

It also runs tests/racket/test but there are some flaky places and
wills tests that require some fixing before merging.

### CODE REVIEW

**Comment by samth** [comment]
Do we really want --enable-xonx? That seems unlikely to be the most important configuration.

**Comment by pmatos** [comment]
> Do we really want --enable-xonx? That seems unlikely to be the most important configuration.

Honestly, I don't know how to build on mac. If I build without `--enable-xonx` and all the other flags, I get a message saying I need `--enable-xonx` or `--enable-macprefix`. I just chose `--enable-xonx` and it seemed to work. What's your suggestion for build parameters on mac?

**Comment by pmatos** [comment]
It seems that `--enable-macprefix` works, so using that instead for now. In any case, there are a couple of flaky tests (sometimes they pass, other times they don't) in `racket/test` that I would really like to ensure they work consistently before getting them merged.

1. Section places: https://github.com/LinkiTools/racket/runs/311655656#step:8:30
2. Section wills: https://github.com/LinkiTools/racket/runs/311655656#step:8:44
3. Section synchronization https://github.com/LinkiTools/racket/runs/311655704#step:8:33

**Comment by pmatos** [comment]
Since the builds are working - would it make sense to push the builds for now to have something in there and add the tests slowly as we make sure they are not flaky? What do others think?

**Comment by samth** [comment]
I'm in favor of that.

**Comment by pmatos** [comment]
@samth thanks - I will split and squash the commits into two. The build part will be merged and the test part with flaky tests will be opened as a new PR.

**Comment by pmatos** [comment]
Merging the build part - opening new PR for testing part.

**Pull request merged**
