### PR TITLE
add xml-attribute-encode function

### PR DESCRIPTION
**Pull request by jbclements**
Per discussion with @jeapostrophe , adds `xml-attribute` encode function (and test, and docs)

### CODE REVIEW

**Comment by jeapostrophe** [comment]
Docs?

**Comment by jbclements** [comment]
Oh ... yep, wrote docs, didn't include them. Hang on.

**Comment by jbclements** [comment]
okay, docs added. Thanks for catching that!

**Comment by jeapostrophe** [comment]
Thanks for catching this!

**Pull request merged**
