### PR TITLE
Remove value store in ready_pos but unread

### PR DESCRIPTION
**Pull request by pmatos**
`ready_pos` is not read after the store of 0. Remove store.

### CODE REVIEW

**Comment by pmatos** [comment]
I went ahead moved the declaration to the block and removed another value that was set but not read, marking it with `(void)tcp...`. Waiting to see results of CI before merging.

**Comment by pmatos** [comment]
oh... xform doesn't like the `(void)tcp_...`. Will have to look at it a bit later.

**Comment by mflatt** [comment]
It's not the `(void)tcp_....` but the `int ready_pos = tcp_check_accept(listener, NULL);`. To accommodate xform, ou'll have to split that to
```
int ready_pos;
ready_pos = tcp_check_accept(listener, NULL);
```

**Comment by pmatos** [comment]
ah, thanks for pointing that out - I didn't have time to look into it yet.

**Comment by pmatos** [comment]
Lets hope xform is happy with https://github.com/racket/racket/pull/2588/commits/b6469e1e1bfe9e522d493b0cf3881c9bdcd43fd2

**Comment by pmatos** [comment]
All good! Merging.

**Pull request merged**
