### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by LeifAndersen** [comment]
Cool. Out of curiosity, is there a nice blog post/other write up that says what azure pipelines has that travis doesn't?

**Comment by samth** [comment]
Just testing it out.

**Comment by chrisrpatterson** [comment]
The major differences are support for all 3 major platforms in one place and a greater concurrency for OSS projects https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/.  I am happy to answer any questions you may have.

**Comment by samth** [comment]
@chrisrpatterson Thanks! One thing that would be helpful for me would be a comprehensive example `azure-pipelines.yml` file, in particular one that included Windows and Mac configuration.

**Comment by pmatos** [comment]
@samth  @chrisrpatterson  I was trying to find the documentation for the azure pipeline yaml and found nothing. Do you have a ref?

**Comment by jeremyepling** [comment]
@pmatos Here are some docs that will be helpful, in addition the reference Chris sent.

- Parallel jobs across platforms. Along with fan-out and fan-in examples. https://docs.microsoft.com/en-us/azure/devops/pipelines/process/multiple-phases?view=vsts&tabs=yaml 
- Templates are another option if you have significantly different build/test steps . https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml
- Here is how libgit2 is doing cross-platform CI https://github.com/libgit2/libgit2/blob/master/.vsts-ci.yml

**Comment by chrisrpatterson** [comment]
@pmatos and @samth here is a PR that fixes the issues I saw in your config https://github.com/racket/racket/pull/2271

**Comment by samth** [comment]
Thanks @chrisrpatterson, that worked perfectly. It took about 21 minutes, which is slightly faster than the usual Travis Linux build.
I'd really like to figure out how to make it work for Windows, though. I haven't seen an example that would let me translate our [AppVeyor.yml](https://github.com/racket/racket/blob/master/appveyor.yml) configuration, though.

**Comment by chrisrpatterson** [comment]
@samth I will take a stab at that a bit later this evening.

**Comment by samth** [comment]
Thanks a ton!

**Comment by LeifAndersen** [comment]
@chrisrpatterson If I'm not too late...

I would like to know if its possible to use Azure Pipelines for CI for projects using Racket. Possibly using something like: https://github.com/greghendershott/travis-racket

**Comment by chrisrpatterson** [comment]
@LeifAndersen you can use it for any open source project

**Comment by LeifAndersen** [comment]
Right. I guess what I'm asking is, is there any way to easily set up Azure pipelines to test your project against multiple versions of a language?

Say, I may want test my project against Racket 6.11, 6.12, and 7.0.

**Comment by samth** [comment]
@LeifAndersen this is pretty easy using roughly the same mechanisms as Travis. If you look at the config that now exists for Racket you should see what's going on.

**Comment by LeifAndersen** [comment]
Okay @samth , thanks. :)

**Pull request merged**
