### PR TITLE
add option to disable constant enforcement for parallel-compile-files, and have raco make use this option when using parallel builds

### PR DESCRIPTION
**Pull request by djholtby**
Proposed solution for #3929

### CODE REVIEW

**Comment by samth** [comment]
Is the first commit here intended/related?

**Comment by djholtby** [comment]
> Is the first commit here intended/related?

Hmmm, no.  I had a pr from years ago that I guess I merged instead of deleting.  Simpler times.  Let me see if I can fix that

**Comment by djholtby** [comment]
(apparently not...)

**Comment by djholtby** [comment]
OK I learned a lot about how to use rebase (and also how not to use rebase).

**Comment by mflatt** [comment]
Thanks!

**Pull request merged**
