### PR TITLE
Suggested revision: Minor documentation edits.

### PR DESCRIPTION
**Pull request by joshuafitzmorris**
Avoid uses of “This”, and add a quick summary of what Racket actually does in the first paragraph.

### CODE REVIEW

**Comment by mflatt** [comment]
Thanks for the suggestion! I've push a variant of your suggestion (I think you probably meant to change or delete par tbefore "Quick Start"), but I'll leave this PR open until we know whether it captures your intent.

**Comment by sorawee** [comment]
Hi @joshuafitzmorris. Does the current README look good to you?

**Comment by koratkar** [comment]
This PR has been open for a few months, should we merge it?

**Comment by sorawee** [comment]
Since there's no response from @joshuafitzmorris , I will assume the current README looks good. Closing.

**Pull request closed without merging**
