### PR TITLE
Add supporting for 1 byte numbers to "integer->integer-bytes" and "in…

### PR DESCRIPTION
**Pull request by rain-1**
Add supporting for 1 byte numbers to "integer->integer-bytes" and "integer-bytes->integer" in racket/src/racket/src/numstr.c

https://github.com/racket/racket/issues/1754

### CODE REVIEW

**Comment by rain-1** [comment]
tested it out with a few values:

```
(integer->integer-bytes #x235E 2 #f)
(integer->integer-bytes #x22 1 #f)
(integer->integer-bytes #xFE 1 #f)
(integer->integer-bytes #x22 1 #t)
(integer->integer-bytes #x7E 1 #t)
(integer->integer-bytes (- #x7E) 1 #t)

(integer-bytes->integer (integer->integer-bytes #x235E 2 #f) #f)
(integer-bytes->integer (integer->integer-bytes 34 1 #f) #f)
(integer-bytes->integer (integer->integer-bytes #xFE 1 #f) #f)
(integer-bytes->integer (integer->integer-bytes #x22 1 #t) #t)
(integer-bytes->integer (integer->integer-bytes #x7E 1 #t) #t)
(integer-bytes->integer (integer->integer-bytes (- #x7E) 1 #t) #t)
```

**Comment by rain-1** [comment]
I wanted to ask if the code is correct, when `sgned` is true it coerces to an unsigned short. 

```c
  case 2:
    {
      if (sgned) {
        unsigned short value = val;
        memcpy(str, &value, sizeof(unsigned short));
      } else {
        short value = val;
        memcpy(str, &value, sizeof(short));
      }
    }
    break;
```

scheme_bytes_to_integer does the opposite:

```c
  case 2:
    if (sgned) {
      short val;
      memcpy(&val, str, sizeof(short));
      return scheme_make_integer(val);
    } else {
      unsigned short val;
      memcpy(&val, str, sizeof(unsigned short));
      val >>= rshft;
      if (mask < 16) { val &= (((unsigned short)1 << mask) - 1); }
      return scheme_make_integer(val);
    }
    break;
```

I may be misunderstanding the code but I thought I'd ask!

**Comment by mflatt** [comment]
@rain-1 I think you're right that the test on `sgned` is backward for the action. The compiler likely generates the same code for both branches, but it doesn't have to.

I'll fold that repair and your tests cases into your commit to merge, and I'll add documentation.

Thanks!

**Comment by mflatt** [comment]
Merged

**Pull request closed without merging**
