### PR TITLE
Remove set, but not used variable

### PR DESCRIPTION
**Pull request by pmatos**
Fixes a warning by gcc

### CODE REVIEW

**Comment by mflatt** [comment]
Unless I misremember or misread the code, `GC_set` doesn't have a side effect, so the call should be removed along with the variable.

**Comment by pmatos** [comment]
@mflatt completely missed your message and forgot about this PR. `GC_set` seems to have a side-effect. Initializing GC, if it's not yet initialized. Shouldn't we keep the call to `GC_set` in that case?

**Comment by pmatos** [comment]
@mflatt ping

**Comment by mflatt** [comment]
That call to GC_set definitely will be after the GC is initialized. I'll commit a change that removes the call.

Thanks!

**Pull request closed without merging**
