### PR TITLE
Fix fasl read fasl string

### PR DESCRIPTION
**Pull request by pmatos**
Add a new test for the failing case.

I noticed the bug with this example:
```
#lang racket

(require racket/fasl)

(define bn 15511210043330985984000000)
(define ser (s-exp->fasl bn))
(define newbn (fasl->s-exp ser))

(printf "~a -> ~e -> ~a~n" bn ser newbn)
```

Racket passes the test with the fix, but fails in the current HEAD.

### CODE REVIEW

**Comment by pmatos** [comment]
@mflatt Can we still get this into 7.1?

**Comment by mflatt** [comment]
How about
```
(define (read-fasl-string i [len (read-fasl-integer i)])
  (define bstr (read-bytes/exactly len i))
  (bytes->string/utf-8 bstr))
```
?

**Comment by mflatt** [comment]
I'm pretty sure that change is a good idea, so I'll merge an adjusted commit.

**Comment by pmatos** [comment]
@mflatt, The change is great, of course. I don't think you need to permission to change my patches. ;) Thanks for merging!

**Pull request closed without merging**
