### PR TITLE
Fix codeql scanning by installing uuid-dev

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Comment by pmatos** [comment]
Good - now passing code scanning!

**Comment by mflatt** [comment]
For the uuid-dev part, Chez Scheme is not supposed to depend on libuuid anymore — but I see that I forgot to update some makefiles. I'll push a makefile repair, and then the install of uuid-dev can be skipped.

**Comment by pmatos** [comment]
> For the uuid-dev part, Chez Scheme is not supposed to depend on libuuid anymore — but I see that I forgot to update some makefiles. I'll push a makefile repair, and then the install of uuid-dev can be skipped.

If you fix this and codeql starts passing I will close this without merging.

**Comment by pmatos** [comment]
Fixed in fcd7295457ba199972089645bb9f698ae6e2bff2 by removing remaining uuid deps. Closing without merging.

**Pull request closed without merging**
