### PR TITLE
added struct/derived

### LINKED ISSUE #1699: Suggestion: struct/contract & struct/derived
I really like contract programming, but was surprised when I noticed there is a define-struct/contract, but no struct/contract. Maybe racket should ship with a struct/contract syntax?

### PR DESCRIPTION
**Pull request by tommymchugh**
This and #2979 resolves #1699

### CODE REVIEW

**Comment by tommymchugh** [comment]
@samth Sounds good! I'll do those.

**Comment by tommymchugh** [comment]
@samth Added!

**Comment by samth** [comment]
Can you add a history note to the docs saying when this was added? There should be other examples in the file.

**Comment by tommymchugh** [comment]
Done! Think I added correctly.

**Comment by samth** [comment]
Looks good. And I'm very impressed by the comprehensive tests. I'll merge after the tests pass.

**Comment by tommymchugh** [comment]
Thanks!

**Pull request merged**
