### PR TITLE
PLT_HTTP_PROXY and PLT_NO_PROXY honoured

### PR DESCRIPTION
**Pull request by tim-brown**
As per conversation on list, `url.rkt` now tries to get its proxy list from `PLT_HTTP_PROXY` (only “http” supported to be consistent with the rest of the proxy server handling). `PLT_HTTP_PROXY` is a URL, of the form: `http://proxy.here.com:3128`.

`PLT_NO_PROXY` stops the proxy from being used for certain sites. In the environment variable, you can enter:
- `hostname.do-serversmainname` as a string, matches the host name exactly
- `.domainname` matches domainname as a suffix of any candidate URL
- I _guess_ that it will support numeric host names, `192.168.1.1`, too; but untested.
- I _guess_ too, that  `.168.1.1` will work too, although I can’t see that being of too much use
- There’s no support for the million and one other IP address patterns/masks/schemes out there

`current-no-proxy-servers` (I use the word servers, since these are all servers that will be proxied to), can be set as a parameter. In this case, a `regexp?` can be provided directly for fancy matching. YMMV on that though..

`proxy-server-for` returns the entry for a scheme and server name (optional); or `#f` for a direct connection

`current-no-proxy-servers` and `proxy-server-for` are exported

### CODE REVIEW

**Comment by jeapostrophe** [comment]
The code looks good. Can you edit the documentation and can you write tests? I imagine that tests will look like this:

Test program side
- Runs the parsing function directly on what would be in the environment

Test program outer
- Sets environment
- Runs system on test program inner
- Captures the output and compares against known good

Test program inner
- Prints out the value of the parameter

**Comment by tim-brown** [comment]
Before I get too committed to this code: Is it right that I do this in racket/racket/collects/net repository (where I'll be doing the tests/docs), rather than the racket/net one? What's the difference?

**Comment by tim-brown** [comment]
[stupid clicking on "close and comment" sorry]

**Comment by jeapostrophe** [comment]
The docs & tests will be in this repository:

https://github.com/racket/net

in the net-test and net-doc packages

**Comment by tim-brown** [comment]
oh, I see... net-lib doesn't have the URL/HTTP client stuff I'm working on

**Comment by jeapostrophe** [comment]
Correct. This part of net is needed to installed packages, so it is here. Everything else in net is in net-lib, but the docs/etc for this part of net are over there in net-doc and net-tests with everything else

**Comment by tim-brown** [comment]
Documentation and Testing in racket/net #6

**Comment by tim-brown** [comment]
are you waiting on me for anything... there was talk of Jay, Matt and (Sam?) deciding whether we go for current-proxy-servers as a parameterised promise (or alt-t)

**Comment by jeapostrophe** [comment]
I was expecting input from others and it didn't come. So maybe they are
busy or don't see a problem...?

On Wed, Oct 28, 2015 at 10:23 AM, Tim Brown <notifications@github.com>
wrote:

> are you waiting on me for anything... there was talk of Jay, Matt and
> (Sam?) deciding whether we go for current-proxy-servers as a parameterised
> promise (or alt-t)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/pull/1089#issuecomment-151860287>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by samth** [comment]
I don't have strong feelings either way, and I'm happy to defer to @jeapostrophe.

**Comment by jeapostrophe** [comment]
I've come around a little bit, I feel like backwards compatibility is good,
but I'm not sure there's any actual examples that we'd be breaking by
making the parameter a promise.

On Wed, Oct 28, 2015 at 11:28 AM, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> I don't have strong feelings either way, and I'm happy to defer to
> @jeapostrophe <https://github.com/jeapostrophe>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/pull/1089#issuecomment-151881571>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by tim-brown** [comment]
There's an example in my .racketrc

But that's not getting read when I need it to (e.g. raco). So I won't be disappointed if I broke compatibility (my principles might be, though)

I'll look at the parameterized promise soon.

Tim

On 28 October 2015 15:35:28 GMT+00:00, Jay McCarthy <notifications@github.com> wrote:
>I've come around a little bit, I feel like backwards compatibility is
>good,
>but I'm not sure there's any actual examples that we'd be breaking by
>making the parameter a promise.
>
>On Wed, Oct 28, 2015 at 11:28 AM, Sam Tobin-Hochstadt <
>notifications@github.com> wrote:
>
>> I don't have strong feelings either way, and I'm happy to defer to
>> @jeapostrophe <https://github.com/jeapostrophe>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/racket/racket/pull/1089#issuecomment-151881571>.
>>
>
>
>
>-- 
>Jay McCarthy
>Associate Professor
>PLT @ CS @ UMass Lowell
>http://jeapostrophe.github.io
>
>           "Wherefore, be not weary in well-doing,
>      for ye are laying the foundation of a great work.
>And out of small things proceedeth that which is great."
>                          - D&C 64:33
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/racket/racket/pull/1089#issuecomment-151884763

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mflatt** [comment]
I'm generally comfortable with these changes. (I'm not clear on the compatibility issues, but it looks like that issue is getting apprrpriate attention.)

**Comment by jeapostrophe** [comment]
To recap for you Matthew:
- Tim's first version is backwards compatible (i.e. existing code that
parameterize the proxy set works) but causes a global effect the first time
you call a function that uses the proxy and sets the parameter based on
parsing the environment variables.
- I think the effect is potentially error-prone and confusing and it would
be more elegant to break backwards compatibility and change the parameter's
value to be a promise of an alist rather than an alist. We can't really
have it both ways because we don't have something that can fake a parameter
on the lhs of parameter. If we could, then we'd do something like this:

(define new-parameter-name
 (make-parameter (promise (parse-the-environment-variables)))
(define old-parameter-name
 (make-wrapper-parameter
  #:write (lambda (new-value) (values new-parameter-name (promise
new-value)))
  #:read (lambda () (force (new-parameter-name)))))

So that

(parameterize ([old-parameter-name 'some-alist]) ...)

is effectively

(parameterize ([new-parameter-name (promise 'some-alist)]) ...)

and

(old-parameter-name)

becomes

(force (new-parameter-name))

STOP THE PRESSES

I went and read the documentation on parameters to see if we could use
chaperones for this and make-wrapper-parameter exists and is called
make-derived-parameter. Matthew, you're amazing. I wanted this feature and
you went back in time and added it!

Tim, I think you should use it and then we'll have the best of both worlds.

Jay



On Wed, Oct 28, 2015 at 3:58 PM, Matthew Flatt <notifications@github.com>
wrote:

> I'm generally comfortable with these changes. (I'm not clear on the
> compatibility issues, but it looks like that issue is getting apprrpriate
> attention.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/pull/1089#issuecomment-151972339>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by tim-brown** [comment]
i'll get to it shortly

**Comment by mflatt** [comment]
@tim-brown Just double-checking: you're planning to do something more here?

**Comment by tim-brown** [comment]
I intend to.
I'm looking at it now (reprioritising thanks to your prompt) hope to have it ready soon

Tim

On 17 November 2015 15:34:33 GMT+00:00, Matthew Flatt <notifications@github.com> wrote:
>@tim-brown Just double-checking: you're planning to do something more
>here?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/racket/racket/pull/1089#issuecomment-157405148

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tim-brown** [comment]
@mflatt, @jeapostrophe -- I’ve pushed this up and unless you have any problems with it; it is compatible with the _documentation_ in racket/net PR#6

BUT... now the little monkey is incompatible with the _tests_ in racket/net PR#6; the environment variables are read when net/url is required. And I can’t flange a `putenv` / `set-environment-variable!` in before that (even with a sandbox); so the tests that test whether environment variables have effect fail.

I can manually get individual tests to pass with `plt_http_proxy=... raco test url.rkt` -- but never the whole test suite.

Advice?

**Comment by jeapostrophe** [comment]
My advice for fixing the tests is to use separate processes and control the
environment they start in.

On Wed, Nov 18, 2015 at 10:01 AM, Tim Brown <notifications@github.com>
wrote:

> @mflatt <https://github.com/mflatt>, @jeapostrophe
> <https://github.com/jeapostrophe> -- I’ve pushed this up and unless you
> have any problems with it; it is compatible with the *documentation* in
> racket/net PR#6
>
> BUT... now the little monkey is incompatible with the *tests* in
> racket/net PR#6; the environment variables are read when net/url is
> required. And I can’t flange a putenv / set-environment-variable! in
> before that (even with a sandbox); so the tests that test whether
> environment variables have effect fail.
>
> I can manually get individual tests to pass with plt_http_proxy=... raco
> test url.rkt -- but never the whole test suite.
>
> Advice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/pull/1089#issuecomment-157740694>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by tim-brown** [comment]
Are there any other components that are tested this way?

Otherwise I'd need details of how to invoke a subprocess (a racket or raco) in the CI environments. How portable is:
(process "racket" "./sub-test-module.rkt")
?

Is there a (load-module-in-new-process ...) form I can use in a cross platform way?

Etc.

Tim


On 19 November 2015 13:32:48 GMT+00:00, Jay McCarthy <notifications@github.com> wrote:
>My advice for fixing the tests is to use separate processes and control
>the
>environment they start in.
>
>On Wed, Nov 18, 2015 at 10:01 AM, Tim Brown <notifications@github.com>
>wrote:
>
>> @mflatt <https://github.com/mflatt>, @jeapostrophe
>> <https://github.com/jeapostrophe> -- I’ve pushed this up and unless
>you
>> have any problems with it; it is compatible with the *documentation*
>in
>> racket/net PR#6
>>
>> BUT... now the little monkey is incompatible with the *tests* in
>> racket/net PR#6; the environment variables are read when net/url is
>> required. And I can’t flange a putenv / set-environment-variable! in
>> before that (even with a sandbox); so the tests that test whether
>> environment variables have effect fail.
>>
>> I can manually get individual tests to pass with plt_http_proxy=...
>raco
>> test url.rkt -- but never the whole test suite.
>>
>> Advice?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/racket/racket/pull/1089#issuecomment-157740694>.
>>
>
>
>
>-- 
>Jay McCarthy
>Associate Professor
>PLT @ CS @ UMass Lowell
>http://jeapostrophe.github.io
>
>           "Wherefore, be not weary in well-doing,
>      for ye are laying the foundation of a great work.
>And out of small things proceedeth that which is great."
>                          - D&C 64:33
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/racket/racket/pull/1089#issuecomment-158057752

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mflatt** [comment]
FWIW, I don't think that's the issue with the tests, but I'm still looking at the patch and tests

**Comment by mflatt** [comment]
To confirm, I don't think a separate process really helps with the tests. I have a working variant, plus a bug fix for a problem exposed by a test. I'm happy to fix up an merge. 
It looks like the `net/url-proxy` module is not intended to be public. Assuming that's correct, I'll move it to a "private" subdirectory.

**Comment by mflatt** [comment]
On closer inspection, it looks like `net/url-proxy` is dead code. I'm not sure that's as intended, but the latest code seems to be in "url.rkt" and not "url-proxy.rkt", so I will remove "url-proxy.rkt".

**Comment by mflatt** [comment]
Merged. I squashed the commits and made adjustments to the docs; hopefully I didn't mangle anything, but please check. Thanks!

**Comment by tim-brown** [comment]
Matt,

(n.b. the message on GitHub is a bcc: of one I've sent to racket users) 

Sorry, I got diverted to other more “urgent” things (he who pays the piper...).  That's why I took so long finishing the job; and rushing at the end, why I left garbage like net/url-proxy in the commit.

So THANK YOU VERY MUCH for doing all that tidying up.

Re the squashing... I assumed that those incremental pushes (each of which I considered to be a worthy candidate for the enhancement) which you guys commented on were not for squashing, since they'd already been committed and pushed to GitHub.

FYI this is the first step in an attempt to get racket to install through an http proxy. And I'll be revisiting net/url-proxy and friends with an http “CONNECT” tunnel soon.

Thanks again,

Tim

On 20 November 2015 03:11:30 GMT+00:00, Matthew Flatt <notifications@github.com> wrote:
>Merged. I squashed the commits and made adjustments to the docs;
>hopefully I didn't mangle anything, but please check. Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/racket/racket/pull/1089#issuecomment-158266404

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
