### PR TITLE
Add support for PowerPC on FreeBSD

### LINKED ISSUE #1471: Racket on PowerPC (FreeBSD)?
Is there a reason why Racket currently doesn't support the PowerPC architecture on FreeBSD? 
I noticed that PowerPC is supported on other operating systems. If it's simply a matter of configuration I can also try to fix it myself.

I know that FreeBSD doesn't have that many users so I understand if porting is not a priority.

### PR DESCRIPTION
**Pull request by alehed**
I'm not sure if this is all that is needed, but it compiles now with freebsd on powerpc.
Closes #1471

### CODE REVIEW

**Comment by alehed** [comment]
Why is the build failing?

**Comment by juanfra684** [comment]
Probably, you want also to add the line: `#define MZ_USE_JIT_PPC`.

Did you try to run DrRacket? Everything works fine?.

If possible, can you run the tests and to copy/paste the output?:
```
$ racket -e '(eval-jit-enabled)'
$ raco pkg install --auto -u racket-test-core
$ cd ~/.racket/$(racket -e '(display (version))')/pkgs/racket-test-core/tests/racket/
$ racket -f quiet.rktl
```

**Comment by alehed** [comment]
Compiling it with `#define MZ_USE_JIT_PPC` gives me the error

```
./../src/jit.c: In function 'scheme_generate':
./../src/jit.c2473: error: 'JIT_LOCAL4' undeclared (first use of this function)
```

**Comment by alehed** [comment]
Without jit enabled the build works. Installing packages works but it complains about not being able to install some documentation. 

The output of `racket -f quiet.rktl` is:
```
Section(basic)


TIMEOUT -- ABORTING!
```

**Comment by juanfra684** [comment]
Build racket with `--disable-places --disable-futures`.

**Comment by alehed** [comment]
Should I disable places and futures by default for the powerpc architecture?

**Comment by stamourv** [comment]
FWIW, those at least used to work on PPC on Mac OS. I last used that combination ~5 years ago, though, and I think we got rid of those build machines some time ago, so it may have bit-rotten.

**Comment by alehed** [comment]
So I'll just disable them in my build script not in the racket configuration file?

**Comment by juanfra684** [comment]
@alehed yes, both are not supported on powerpc. With both disabled in the configure script, you can build the interpreter with JIT.

@stamourv look #1239.

**Comment by stamourv** [comment]
Ah, looks like I was out of date then. :)

**Comment by alehed** [comment]
I cloned racket, changed freebsd on ppc in the sconfig to contain:
```
#define SCHEME_PLATFORM_LIBRARY_SUBPATH "ppc-freebsd"
#define MZ_USE_JIT_PPC
```
And built it with `make`. I get the error: `http-client: connection ended early`. Any thoughts on this?
Note that by default both futures and places are disabled on ppc.

**Comment by alehed** [comment]
Building it with the ports system (minima-racket) with the above sconfig and without places or futures I get an error in racket3m:
```
/usr/ports/lang/racket-minimal/work/racket-6.6/src/racket/.libs/racket3m: Undefined symbol "GC_variable_stack"
```

**Comment by alehed** [comment]
I finally got a build working with JIT enabled (I didn't give it any JIT flags like msse, msse2 or mfpmath=sse). The output of eval-jit-enabled ist true. 
I have to say, my racket interpreter is pretty slow. When I execute the given test, the output is still the same as when I ran it the first time (see above).
BTW: I installed racket-minimal and I'm running freebsd without a window system so I don't know if DrRacket would work or not.

**Comment by alehed** [comment]
I was also mistaken about the default build. On PowerPC you specifically have to specifically disable places and futures, otherwise it doesn't work.

**Comment by juanfra684** [comment]
The reason why I asked for the tests is because racket crashes on OpenBSD/macppc. I installed FreeBSD 10.2 and I see the same crash in the same test (`racket -f unsafe.rktl`). Something is broken in the powerpc JIT or GC code (the same test works fine without the JIT but other different tests fail).

That said, I think that the PR is correct and someone should commit the changes.

**Comment by alehed** [comment]
Yes, for me it also crashed on that test. 

Btw: Is it normal that a simple hello world in racket takes about 2s on an old computer (~700 according to geekbench)?

**Comment by juanfra684** [comment]
Try this: `echo '#lang racket/base\n(displayln "hello world")' > hello.rkt && raco make hello.rkt`.  Then run `racket hello.rkt`, it will avoid the slow cold start. BSDs on powerpc are usually slow, I don't know how Apple made OSX fast on these machines.

**Comment by rfindler** [comment]
If you run `raco make -v hello.rkt` (adding the `-v` flag) and you see lots and lots of output, that means that probably you missed a step in the build process. (You would see all this output only the first time you run the command; but you know it was there if the command gets a lot faster the second time.)

**Comment by alehed** [comment]
Compiling reduces the two seconds to about one and a half.

On `raco make -v` the output shows nothing unexpected. On `raco make --vv` I get almost 300 lines of `checking: ...` but also that seems quite expected.

But to be honest, it's not such a big deal for me. As long as it works, I'm happy.

**Pull request merged**
