### PR TITLE
reqprov: fix disappeared-use

### PR DESCRIPTION
**Pull request by sorawee**
This PR fixes several issues regarding disappeared-use in reqprov.rkt

<s>1. Add `disappeared-use` for each exported identifier expanded from
`all-defined-out` with a syntax location of `all-defined-out` so that
Check Syntax can draw arrows from definitions to `all-defined-out`.</s>

2. Copy/preserve disappeared-use for all provide subforms instead
of only the first one. The following program doesn't have an arrow from
`struct-out` to `#lang racket` prior this PR, but it does after this PR.

        #lang racket
        (provide a? (struct-out a))
        (struct a ())

3. Fix incorrect `disappeared-use` for `struct-out`: it is inappropriate
to check if an identifier is bound to a struct info in provide
pre-transformer because it would not be able to handle backlinks.
This PR moves the attachment from provide pre-transformer to provide
transformer, allowing Check Syntax to draw an arrow for the identifier
`abc` in:

       #lang racket
       (provide (struct-out abc))
       (struct abc ())

### CODE REVIEW

**Comment by sorawee** [comment]
CC: @mflatt and @rfindler. Hopefully the diff will be easier to read this time.

**Comment by rfindler** [comment]
Probably you want to write some test cases (for the new behavior). Sadly they wouldn't go in this repo but there is some [code here](https://github.com/racket/drracket/blob/master/drracket-tool-test/tests/check-syntax/syncheck-direct.rkt) that you can add to.

**Comment by sorawee** [comment]
I did include some tests (see https://github.com/racket/racket/pull/3391/files#diff-20b0e3ab5f7a3c0c96abc2ed491d0207), but I can add more tests in DrRacket too.

**Comment by rfindler** [comment]
Oh! Sorry. It did seem like a lot of changes for what was in the description. :)

**Comment by sorawee** [comment]
I updated the PR so that the PR is strictly bug fixing and could be readily merged. Particularly, I remove changes to `all-defined-out` since the changes will break the renaming functionality in Racket Mode, and fixing it requires https://github.com/racket/drracket/pull/417 to be integrated first.

**Comment by rfindler** [comment]
This diff is backwards, right? I'm not going crazy?

Screen Shot 2020-09-09 at 6 31 24 PM

**Comment by sorawee** [comment]
Well, I reverted the changes, so it's supposed to be backwards! If you look at the overall diff, there should be no change in those areas (well, there's an unfortunate whitespace change on one line...)

**Comment by sorawee** [comment]
Ping, any thoughts on this? It's been a month.

**Pull request merged**
