### PR TITLE
add more plugins to emacs section of guide

### PR DESCRIPTION
**Pull request by willghatch**
Due to the recent mailing list conversation about emacs plugins for working with Racket, I thought I would add a little to the guide section about it.  In particular this adds some packages that I find useful for evil-mode users.  Perhaps there should be a separate bullet list of packages that are useful specifically for evil-mode users?

### CODE REVIEW

**Comment by stamourv** [comment]
Would it make sense to combine those into one `evil-racket-support` emacs package or something? Otherwise, it's kind of a scattering of stuff.

**Comment by willghatch** [comment]
Perhaps.  I can see the appeal of keeping a short list.  But at the same time I'm generally not keen on emacs packages that just configure some other packages.  Personally I have some extra configuration for each of these packages, and any configuration in an `evil-racket-support` package would just be something I would be fighting.  I think it would be useful to have just a long list of editor plugins/configuration/etc that people find useful, but maybe the guide could just point to it.  Maybe somewhere in a wiki.

**Comment by stamourv** [comment]
How about a general `evil-mode` bullet? Puts everything related to it in the same place, and easy to skip for people who don't use it.

**Comment by willghatch** [comment]
Agreed.  How about this update?

**Comment by stamourv** [comment]
LGTM

**Pull request merged**
