### PR TITLE
Add more hash-like operations to id-tables

### PR DESCRIPTION
**Pull request by takikawa**
The operations are ref!, set*, set*!, update, and update!. Also bumps version number.

### CODE REVIEW

**Comment by stamourv** [comment]
LGTM

**Comment by rmculpepper** [comment]
What's wrong with the generic versions of these functions from `racket/dict`?

**Comment by takikawa** [comment]
The `racket/dict` library adds a lot of overhead due to contracts. I'm trying to remove uses of dict functions from TR in favor of specialized operations to speed up typechecking.

**Comment by mflatt** [comment]
This is ok with me.

**Pull request merged**
