### PR TITLE
skip-installed from all scopes, not current

### PR DESCRIPTION
**Pull request by wilbowma**
closes issue #1115

### CODE REVIEW

**Comment by samth** [comment]
This looks nice and simple to me. @mflatt or @jeapostrophe?

**Comment by wilbowma** [comment]
Investigating the failure

**Comment by wilbowma** [comment]
Okay, this should work. Also, added a test case for it.

**Comment by wilbowma** [comment]
Looks like previous failure had to do with hashes, not something I changed; rebasing to master.

**Comment by wilbowma** [comment]
All tests pass! Going to drop the whitespace changes, per concern about `git blame`.

**Comment by rfindler** [comment]
(FWIW, I wish that whitespace wasn't there in the first place and I remove
it when I edit lines and thanks to Max, DrRacket doesn't include it anymore
.... sigh)

**Comment by jeapostrophe** [comment]
LGTM

**Pull request merged**
