### PR TITLE
typo: is-flat-contract? -> is-list-contract?

### PR DESCRIPTION
**Pull request by bennn**
While we're here, can I put the 6 accessors into an `@itemlist`?

### CODE REVIEW

**Comment by rfindler** [comment]
Go for it. And feel free to just push the change.

**Comment by bennn** [comment]
I don't have push access. :frowning:

**Comment by rfindler** [comment]
Okay, well let me know when you're happy and I'll push.

**Comment by bennn** [comment]
I'm happy

**Comment by rfindler** [comment]
Thanks, I've pushed it.

**Pull request closed without merging**
