### PR TITLE
gzip: use path-add-extension as default

### PR DESCRIPTION
**Pull request by bennn**
Instead of `string-append`-ing the extension, because that doesn't work for all path strings

### CODE REVIEW

**Comment by mflatt** [comment]
LGTM

**Comment by bennn** [comment]
Right. (I should have said that in a comment.)

What about adding an optional byte string argument to `path-add-extension` to  replace `_`?

**Comment by mflatt** [comment]
That addition sounds ok to me.

**Comment by bennn** [comment]
- changed `path-add-extension`to accept an optional 3rd argument
- `gzip` uses the 3rd argument, so zipping `x.tar` gives `x.tar.gz`
- added `@history` annotations for both changes

Docs building now, will post screenshots when they're finished

**Comment by bennn** [comment]
Is `6.8.0.2` the right version to cite?

screen shot 2017-03-25 at 20 31 58
screen shot 2017-03-25 at 20 34 11

**Comment by mflatt** [comment]
This looks ready to push to me.

**Comment by bennn** [comment]
Thanks for looking it over; merged via https://github.com/racket/racket/commit/2cbd44d64d815faeb939421cf448fbe2ae7635d0 and https://github.com/racket/racket/commit/30aa951db886dd4e6ac4d1630a0d2e42d035085b

**Pull request closed without merging**
