### PR TITLE
Add a missing property to an expression lifted by the contract system.

### PR DESCRIPTION
**Pull request by stamourv**
Caused TR to miss it.

Submitted as a PR pending changes to TR.

### CODE REVIEW

**Comment by rfindler** [comment]
Is TR generating `opt/c` contracts?

**Comment by samth** [comment]
This isn't for contracts TR generates, but for contracts on functions used in typed modules.

**Comment by rfindler** [comment]
Are you saying that someone is writing `opt/c` in TR code and then TR uses
that as a contract?

**Comment by samth** [comment]
No. @stamourv can give you the actual code that ran into this issue, but what's happening here is that some code in the Racket standard library, unrelated to TR, uses these contract features. Then the function with that contract is used in a typed module, which causes the expander to lift some things. TR attempts to ignore that code while type checking, but the relevant annotation was missing in this case, so TR did the wrong thing.

**Comment by rfindler** [comment]
Ah, got it.

This seems fine to push (please don't use a merge commit -- I can do it if
you want)

**Comment by stamourv** [comment]
FWIW, one of the failing tests was using `~r` and other functions from `racket/format` in TR code. Those functions have contracts, and so their call sites in the typed module triggered some lifts.

**Comment by stamourv** [comment]
Merged.

**Pull request closed without merging**
