### PR TITLE
A few small fixes.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by mflatt** [comment]
LGTM

**Comment by samth** [comment]
@mflatt I just added another commit here -- can you take a look?

**Comment by mflatt** [comment]
I'm less enthusiastic about that one. Would it make sense to move `read-eval-print-loop` to its own module, so you can `#%require` it in a module that starts with `#%kernel`?

**Comment by samth** [comment]
Isn't that what the change does? I think using `delete-trailing-whitespace` in emacs produced too big a diff -- I'll fix that.

**Comment by samth** [comment]
Ok, thanks. I reworded the commit message to avoid the misunderstanding, and I'll merge when CI completes.

**Comment by samth** [comment]
The AppVeyor failure is something else, and the Travis failure is something transient with weak tables.

**Pull request merged**
