### PR TITLE
[doc] link max <--> argmax

### PR DESCRIPTION
**Pull request by bennn**
This is the right look, but is it possible to use a `seclink` instead of the `for-label` import?

### CODE REVIEW

**Comment by bennn** [comment]
cc #1622 

previews:
screen shot 2017-03-11 at 13 35 24
screen shot 2017-03-11 at 13 35 44

**Comment by rfindler** [comment]
I think we usually put the "see also"s into the description, not in the
sidebars.

Robby

**Comment by bennn** [comment]
New commit, new previews:

screen shot 2017-03-11 at 14 00 28
screen shot 2017-03-11 at 14 04 16

**Comment by bennn** [comment]
One more, in standard "see also" style.

screen shot 2017-03-11 at 14 10 16
screen shot 2017-03-11 at 14 10 27

**Comment by bennn** [comment]
@rfindler ping, do you like the most recent revision?

**Comment by rfindler** [comment]
Yes

**Pull request merged**
