### PR TITLE
Remove OS/2 support

### PR DESCRIPTION
**Pull request by mmcco**
OS/2 is a long-defunct operating system, but Racket still contains a
bunch of compat code for it.

### CODE REVIEW

**Comment by mmcco** [comment]
I need to change my name and email in the commit. Doing so now. Please don't merge until I get a chance to.  :-)

**Comment by mmcco** [comment]
Also, looks like I mistakenly removed a couple parens in closures.c. I'll replace those once I fix my commit info.

**Comment by mflatt** [comment]
Hi @mmcco – I just took a look at your changes for the first time. I'm happy to remove Racket-specific code for OS/2. The "libffi" and "gc" directories are really third-party libraries, though, and I think it makes less sense to remove code there.

**Comment by mmcco** [comment]
Oh, right. This was my first time working with the Racket codebase, so I didn't notice. All of the instances were in libffi or gc, so I'll close this PR.

**Pull request closed without merging**
