### PR TITLE
raco pkg: Don't show "Invalid answer" for "?"

### PR DESCRIPTION
**Pull request by sorawee**
Related to #4393

### CODE REVIEW

**Comment by otherjoel** [comment]
(Could the response also be updated to use `'` instead of the annoying backticks-as-fake-curly-quotes?)

**Comment by sorawee** [comment]
Done.

**Comment by mflatt** [comment]
I would have either left this as

```
`x'
```

or changed to

```
`x`
```

but not

```
'x'
```

The first form was the convention for Racket messages for a long time (the first decade or two), where the intent was to make something that didn't look like an S-expression to help clarify that the content is meant as literal. Since Markdown became popular and literalness with backquotes is widely understood, we moved to the second backquote convention. I've been converting the old forms only gradually, though, because I always worry that something may be relying on exact text.

Any objection to changing to the backquote form here?

**Comment by sorawee** [comment]
I can change it to backtick.

**Comment by shhyou** [comment]
I wonder whether using actual quotes i.e. `‘’` and `“”` could be better. Backticks are also used for starting commands in many shells, so I'm worried that printing pairs of backticks may create security problems when the outputs accidentally ended up in the shell. That said, I don't know any immediate issues.

**Pull request merged**
