### PR TITLE
Check for mutated struct predicates.

### PR DESCRIPTION
**Pull request by samth**
Related to #3899.

### CODE REVIEW

**Comment by mfelleisen** [comment]
I wonder whether we could have a "dirty" bit per struct and then just pay the price for all accessors if any one of them has been mutated.

**Comment by samth** [comment]
I think that would involve a runtime test, whereas this approach will be entirely optimized away.

**Comment by mfelleisen** [comment]
You are generating n run-time tests if I read this code correctly:

```
  #`(if (variable-reference-constant? (#%variable-reference #,pred))
                                (λ (x) (unsafe-struct-ref x #,i))
                                #,acc))
```

 I am proposing to generate one but punish the entire suite of accessors at once.

**Comment by samth** [comment]
That code will always be optimized to just the true or just the false branch at compile time.

**Comment by samth** [comment]
@racket/release should we include this in 8.2?

**Comment by mflatt** [comment]
I think it makes sense to include this in v8.2.

To help confirm that the amount of generated code is ok: a build plot before and after the change shows no difference (i.e., in the noise) for build time or memory use on x86_64 Mac OS.

**Comment by jbclements** [comment]
picked, thanks.

**Pull request merged**
