### PR TITLE
wrapped openssl's sha-256

### PR DESCRIPTION
**Pull request by eu90h**
@samth here you go :)
 sorry about closing #1055, just couldn't think of another way.

### CODE REVIEW

**Comment by eu90h** [comment]
AppVeyor failure: `Build execution time has reached the maximum allowed time for your plan (40 minutes).`

**Comment by mflatt** [comment]
I'm not opposed to this addition, but I wonder whether it would be better to add it in a separate package (while `openssl/libcrypto` should be documented so that packages can reasonably depend on it)

**Comment by eu90h** [comment]
Improved the wrapper slightly, making better use of the FFI libs (thanks @samth). 

Where would a better place for this be @mflatt? Or do you mean I should just make it a package and submit it to the index?

**Comment by mflatt** [comment]
@eu90h Yes, I think this library makes sense as a new package. I've finally added documentation for `openssl/libcrypto`.

**Comment by eu90h** [comment]
Understood. Thanks for for documenting libcrypto. I'll go ahead and close this.

**Pull request closed without merging**
