### PR TITLE
update other-editors guide with modern vim references.

### PR DESCRIPTION
**Pull request by benknoble**
After some Discord chatting, I realized this page was woefully out of date. Here are some attempts at updates.

/cc @spdegabrielle

### CODE REVIEW

**Comment by benknoble** [comment]
I did not have a great time testing the docs locally, but there' s probably a better process. `raco scribble --dest oe other-editors.scrbl && open oe/other-editors.html` showed the red squigglies under `#lang` and `racket` and `at-exp`. I am probably missing `for-label` references. Not sure which ones to add.

**Comment by sorawee** [comment]
FWIW, this is what I see when building with `raco setup scribblings/guide`: [24.3 Vim.pdf](https://github.com/racket/racket/files/7696104/24.3.Vim.pdf)

**Comment by benknoble** [comment]
> FWIW, this is what I see when building with `raco setup scribblings/guide`: [24.3 Vim.pdf](https://github.com/racket/racket/files/7696104/24.3.Vim.pdf)

Great, that looks like the references were all correct then! 😄

**Comment by mflatt** [comment]
Thanks for the update.

Nit: the capitalization of `Vim` looks inconsistent. Should it be `Vim` everywhere or `vim` everywhere?

**Comment by benknoble** [comment]
> Nit: the capitalization of `Vim` looks inconsistent. Should it be `Vim` everywhere or `vim` everywhere?

I… am not sure. I habitually write vim, but https://www.vim.org/ consistently writes Vim, so I need to correct both the document and the habit :)

**Comment by benknoble** [comment]
@mflatt corrected. I also added a section on REPLs.

**Pull request merged**
