### PR TITLE
Add configure option --enable-generations (enabled by default).

### PR DESCRIPTION
**Pull request by pmatos**
This option allows the user to enable or disable (with
--disable-generations or --enable-generations=no) generations in
gc2. This is, in most cases, a bad idea.

### CODE REVIEW

**Comment by mflatt** [comment]
This looks like the right idea. Before merging, though, I'd like to see how much difference it makes to further adjust the GC for single-generation mode, and I should be able to get to that today.

**Comment by pmatos** [comment]
This just failed on AppVeyor... 
```
c:\projects\racket\racket\src\racket\gc2\newgc.c(772) : error C2065: 'USE_GC_GENS' : undeclared identifier
failed compile
```

Doesn't fail on Linux. Interesting...

**Comment by mflatt** [comment]
There's a "mzconfig.h" in "racket/src/worksp" that needs to be manually updated (since we don't try to use `configure` on Windows).

**Comment by pmatos** [comment]
ah, thanks.

**Comment by pmatos** [comment]
OK, updated. This is an untested commit as I don't have a windows machine at hand, hopefully CI will check all is ok.

**Comment by pmatos** [comment]
Argh, of course. Because we don't have configure or preprocessing of this header we need to hardcode the correct value for `USE_GC_GENS`.

**Comment by mflatt** [comment]
Thanks! I'll merge this (squashed) with a few small changes:

 * Adjust `configure` help to fit in 80 columns

 * Add a `show_explicitly_disabled`, which compensates some for the lack of argument checking by confirming when the flag is spelled correctly

 * Drop signal-handling code in the GC when it's not going to be used

 * Adjust the commit message to explain when disabling generational GC might be a good idea

Finally, I'll add another commit that adjusts the GC heuristic to better fit no-generations mode. DrRacket is more usable that way, for example.

**Comment by pmatos** [comment]
Thanks. I will close the PR.

**Pull request closed without merging**
