### PR TITLE
Fix rerequire reload on changed dependencies

### PR DESCRIPTION
**Pull request by djholtby**
Fix for #3925 (maybe #971)

mflatt pointed me to `resolve-module-path-index` being needed to rebase the module-path-index attached to the exports of  .zo files (which is always relative to themselves)

### CODE REVIEW

**Comment by djholtby** [comment]
While I was poking at it I noticed it was reloading files that have submodules multiple times, bf68c45 adds a second hash table to solve this so that each that needs a reload is loaded only once.

**Comment by mflatt** [comment]
Thanks for this repair!

Some tests for this module are in `pkgs/racket-test/tests/racket/rerequire.rkt`. The tests there currently are not at all exhaustive, but I started the test suite when adding a previous repair. Would it make sense to add some tests there?

**Comment by djholtby** [comment]
Very likely -
One change needed is instead of checking for a non-empty list, it should
check specifically that both one.rkt and two.rkt were reloaded (in case
it's only reloading the changed file, but not ones that depend on it, which
is the issue I was having).
Another is to try different combinations of files with only source
available, and files that have been compiled.

I've done both here:
https://github.com/djholtby/racket/blob/additional-rerequire-tests/pkgs/racket-test/tests/racket/rerequire.rkt

I also added a "zero" file in a different directory to make sure it's
changing directories without issue.  Not that I think that makes a
difference, but still.

The last few commits are my descent into madness as I try to make sure it's
not "hard coding" the location of the compiled files.
I settled on using a regexp to look for something that looks vaguely like a
compiled version of the target file.

**Comment by djholtby** [comment]
OK, I found the proper way to locate the compiled file name.  (I think)
Added a reworked test file.  

Without the repair all of the tests fail on Windows 10 and Ubuntu 20.04  (even the "all source" test) at the reload stage, so using 3 files wasn't excessive after all.  
(However doing all 16 permutations of compiled and source is probably excessive).

**Comment by mflatt** [comment]
Thanks!

**Pull request merged**
