### PR TITLE
Add --no-docs command line to `raco pkg install`

### PR DESCRIPTION
**Pull request by pmatos**
This simply passes the same flag to setup, which already knows how to
run setup without rendering the documentation.

### CODE REVIEW

**Comment by pmatos** [comment]
I have been wishing someone got this done for over a year. It was time to get it done so hopefully this is ok. It certainly cuts `frog` (from clean racket install) installation time by 40% on my machine.

**Comment by pmatos** [comment]
I might have made a mistake in the push... why is `configure` changed? huh - let me check it out.

**Comment by pmatos** [comment]
Fixed it - sorry for that. Guess when you start pushing the wrong changes, it's better to stop for the day. Nothing good can come after that. ;)

**Comment by pmatos** [comment]
Of course... I remembered the docs while going for a walk with my wife - was hoping you hadn't noticed it yet! Let me add that now.

**Comment by pmatos** [comment]
Docs added in https://github.com/racket/racket/pull/2776/commits/3012a030351d1592657456c1c6838c35a61784ae

**Comment by bennn** [comment]
Does `-D` work too? (because `raco setup` accepts `-D` or `--no-docs`)

**Comment by pmatos** [comment]
@bennn true. I forgot that. Stay tuned. -D coming soon to a repo next to you.

**Pull request merged**
