### PR TITLE
Remove hash-filter

### PR DESCRIPTION
**Pull request by sorawee**
`hash-filter` conflicts with a user package,
which blocks the 8.13 release

CC: @dr-neptune @AlexKnauth @samth @mflatt

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Would it make sense to only apply this revert to the release branch?

**Comment by AlexKnauth** [comment]
Or even, keep `hash-filter-keys` and `hash-filter-values`, and just not provide `hash-filter` yet until the conflict is resolved?

**Comment by dr-neptune** [comment]
> Or even, keep `hash-filter-keys` and `hash-filter-values`, and just not provide `hash-filter` yet until the conflict is resolved?

That would be great if it's a path forward. If this is fine, should I make a PR to remove `hash-filter`? Is there an easy way to cherry pick which changes are reverted?

**Comment by sorawee** [comment]
> > Or even, keep `hash-filter-keys` and `hash-filter-values`, and just not provide `hash-filter` yet until the conflict is resolved?
> 
> That would be great if it's a path forward. If this is fine, should I make a PR to remove `hash-filter`? Is there an easy way to cherry pick which changes are reverted?

I repurposed this PR to do exactly this.

**Comment by mflatt** [comment]
Yes, let's merge this and merge to the release branch. We can revert this change in the future if `hash-filter` becomes no longer a collision.

**Comment by sorawee** [comment]
John, could you merge this to the release branch? Thanks! @jbclements

**Comment by jbclements** [comment]
Yep, got it.

**Comment by jbclements** [comment]
picked. I'm going to try to get my release notes in before starting another build.

**Comment by AlexKnauth** [comment]
Can `hash-filter` be re-instated now that the conflict is resolved by https://github.com/prozion/odysseus/pull/2?

**Comment by jbclements** [comment]
Sounds like a good idea to me. Not for v8.13, of course...

**Pull request merged**
