### PR TITLE
Extend the information in info-lang.

### PR DESCRIPTION
**Pull request by LeifAndersen**
This way people can install different packages based on there system.

### CODE REVIEW

**Comment by stamourv** [comment]
This should be documented and tested.
Also, *their*.

**Comment by LeifAndersen** [comment]
> This should be documented

It is, this commit extends the documentation

> and tested

So, I don't know if there are any unit tests in the code base itself. But I did test it on some of @soegaard 's poppler packages. And it seemed to work just fine.

**Comment by stamourv** [comment]
Re docs: I should have been clearer. What I meant was that the use case for those should be documented. I.e., "If you want a package that ... then use ..."
Re tests: The pkgs tests are at: `pkgs/racket-test/tests/pkg/`

**Comment by mflatt** [comment]
@LeifAndersen It might be ok to add `if`, etc., but I wonder whether you're trying to set up platform-specific dependencies. If so, use the `#:platform` modifier on a dependency, instead of producing a conditional result.

**Comment by LeifAndersen** [comment]
@mflatt Ah, I didn't see the #:platform keyword. Although that doesn't seem to solve all of the problem, because what if I wanted different packages for if I was on a 32 bit vs a 64 bit system? #:platform seems to only give one of 'unix, 'osx, or 'windows.

**Comment by mflatt** [comment]
No, `#:platform` supports more specific platform strings, which is why the `gui-lib` package can call pull in the right Pango implementation for 32-bit Windows versus 64-bit Windows, and so on.

**Comment by LeifAndersen** [comment]
Oh cool, thanks.

**Pull request closed without merging**
