### PR TITLE
Fix #2885: convert number entity to character

### LINKED ISSUE #2885: read-xml discards data
Some XML documents (in my case these are XML files from [MediaWiki API](https://www.mediawiki.org/wiki/API:Main_page)) encode newline with `&#13;&#10;`. For instance:

```
<?xml version="1.0"?>
<blah foo="1 &amp;&#13;&#10;2" />
```

should contain an encoding of the string:

```
1 &
2
```

The problem is that `read-xml` completely discards `&#13;&#10;`, so it's impossible to recover the newline back. 

Here's a demonstrating Racket program:

```
#lang racket

(require xml)

(define x #<<EOF
<?xml version="1.0"?>
<blah foo="1 &amp;&#13;&#10;2" />
EOF
  )

(read-xml (open-input-string x))
```

This outputs:

```
(document (prolog (list (p-i (location 1 0 1) (location 1 21 22) 'xml "version=\"1.0\"")) #f '()) (element (location 2 0 23) (location 2 33 56) 'blah (list (attribute (location 2 6 29) (location 2 30 53) 'foo "1 &2")) '()) '())
```

Note that the `sxml` package retains the data and in fact even convert them to newline automatically:

```
#lang racket

(require sxml)

(define x #<<EOF
<?xml version="1.0"?>
<blah foo="1 &amp;&#13;&#10;2" />
EOF
  )

(ssax:xml->sxml (open-input-string x) '())
```

outputs:

```
'(*TOP* (*PI* xml "version=\"1.0\"") (blah (@ (foo "1 &\r\n2"))))
```

### PR DESCRIPTION
**Pull request by sorawee**
CC: @jeapostrophe

### CODE REVIEW

**Comment by sorawee** [comment]
I see the error in this PR, but I want to disagree with these errors.

The grammar of xexpr is that each attribute must be a string. This dictates that I must convert `10` to `\n` in attributes to make it representable in the grammar.

But if I should/could do that, then what's the justification of keeping `10` in the body of xml? Since we need to convert `10` to `\n` at some places already anyway, why don't we do it on all of them? What's the point of keeping `10` at only some places and not the other?

**Comment by jeapostrophe** [comment]
Thank you! Good change.

**Comment by sorawee** [comment]
@jeapostrophe this PR is actually bad. There's a bug when I copied and pasted the code.`(string ...)`  should be changed to `(list ...)`. Otherwise, there will be an error:

```
append: contract violation
  expected: list?
  given: "("
```

But this also clearly means that the new test that I added didn't get run. Do you know what's going on?

**Comment by jeapostrophe** [comment]
I fixed it.

**Comment by sorawee** [comment]
Thanks! So the other question is, do you know how to make the test working properly?

**Comment by jeapostrophe** [comment]
Are you talking about the CI build? I have no idea about that. DrDr will run it though.

**Comment by sorawee** [comment]
Yep, I am talking about the CI build. I'll try to see if there's a way to make it work.

**Comment by pmatos** [comment]
@sorawee sorry for the delay here. Just returned from a week holidays. Are you talking about the gitlab CI system? If you need some tests to run there, I can make it happen.

**Comment by sorawee** [comment]
@pmatos Yes, I attempted to fix it at #2887, but it didn't work. Obviously, I don't understand the testing infrastructure well enough. If you could make it work, that would be really great.

In short: every file in the directory `tests/xml` that has the `test` submodule should be tested, but currently only `tests/xml/test.rkt` is run.

**Comment by samth** [comment]
The problem is that you kept -l as the flag to raco test. You might want
-c, but probably better to just make that file require the others.

**Comment by pmatos** [comment]
> The problem is that you kept -l as the flag to raco test. You might want -c, but probably better to just make that file require the others.

@sorawee let me know if you want to go ahead and do this or if you want me to. Lets not deadlock on this issue.

**Comment by sorawee** [comment]
@pmatos please do it!

**Comment by pmatos** [comment]
> @pmatos please do it!

Will do.

**Comment by pmatos** [comment]
@sorawee done under https://github.com/racket/racket/commit/1eb64f3961c879d7a6dd161b7a4a37829340d7d4

**Comment by sorawee** [comment]
Thanks! :)

**Pull request merged**
