### PR TITLE
generics: optional scope argument for private macros

### PR DESCRIPTION
**Pull request by AlexKnauth**
To make them more friendly to macros that expand to generics.

This is related to my [email on the racket-dev list][racket-dev-email] on macros expanding to generics, and would allow me to solve my problem there.

Currently, the `gen:interface` identifier serves two purposes: getting the info for the generic interface, and setting the scope for the method implementations. This pull request separates these two purposes into two separate identifiers, so that macro implementors can choose to pass a scope identifier with different scopes from the generic-interface identifier.

  [racket-dev-email]: https://groups.google.com/forum/#!topic/racket-dev/JAXrLTEOrpE

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Some of the Travis builds are failing because they're having trouble connecting to `www.unicode.org`.

**Comment by mflatt** [comment]
This looks like a fine change to me (and just needs docs and tests to merge).

**Comment by AlexKnauth** [comment]
This only modifies undocumented internal macros, so what would I do for docs?

I'll add some tests.

**Comment by stchang** [comment]
> what would I do for docs?

Perhaps a better question would be, there's a few examples now that use forms from `private/generic-methods`. Would some of those forms be worth moving to `racket/generic` and documenting them?

**Comment by mflatt** [comment]
I agree with @stchang. I didn't catch that a private module is being used, so maybe it's ok to just have tests for now, but it sounds like something needs to be made public and documented.

**Comment by AlexKnauth** [comment]
Should it be made public in a separate pull request?

**Comment by mflatt** [comment]
Yes, a separate PR sounds good

**Comment by AlexKnauth** [comment]
So should this one be merged?

**Comment by mflatt** [comment]
Yes

**Pull request merged**
