### PR TITLE
list: ensure eqness of remove op and improve doc

### PR DESCRIPTION
**Pull request by sorawee**
If the cost of `call/cc` is not worth the eq-ness guarantee, I can abandon the change.

### CODE REVIEW

**Comment by samth** [comment]
You could write this with an accumulator and without call/cc (effectively that's cps + defunctionalization).

**Comment by mflatt** [comment]
A common approach is to check whether the recursive `loop` call returns a value `eq?` to its argument, and return the original argument in that case.

**Comment by sorawee** [comment]
Done! I followed @mflatt's approach.

**Comment by samth** [comment]
Can you add a test for the eqness property?

**Comment by mflatt** [comment]
Also, it would be good to add a `history` note to mention when the same-result guarantee was added. Thanks for this improvement!

**Comment by sorawee** [comment]
Done. Thanks for the feedback!

**Comment by sorawee** [comment]
I also changed `remove*` to preserve eqness as well.

**Comment by mfelleisen** [comment]
Curiosity. Is a let/ec really more expensive than N eq? tests?  I am almost sure there's a cut-off point somewhere.

**Comment by sorawee** [comment]
It also depends on the implementation. I know that in Racket CS, `call/ec` is more expensive than `call/cc`, while the opposite is true in Racket BC.

**Comment by mfelleisen** [comment]
I couldn't resist :-) 

```
#lang racket/base

(define-syntax-rule (tester do-remove)
  (begin
    (collect-garbage)
    (collect-garbage)
    (collect-garbage)

    (time 
     (let tester ([n 10])
       (when (> n 0)
         (define lst (build-list LIMIT values))
         (eq? (do-remove-letec -1 lst =) lst)
         (tester (- n 1)))))))
  
(define (do-remove-letec item orig-list equal?)
  (let/ec k
     (let loop ([list orig-list])
       (cond [(null? list) (k orig-list)]
             [(equal? item (car list)) (cdr list)]
             [else (cons (car list) (loop (cdr list)))]))))

(define (do-remove-callcc item orig-list equal?)
  (let/cc k
     (let loop ([list orig-list])
       (cond [(null? list) (k orig-list)]
             [(equal? item (car list)) (cdr list)]
             [else (cons (car list) (loop (cdr list)))]))))

(define (do-remove-eq item orig-list equal?)
  (let loop ([list orig-list])
    (cond [(null? list) '()]
          [(equal? item (car list)) (cdr list)]
          [else
           (define r (loop (cdr list)))
           (if (eq? (cdr list) r)
               list
               (cons (car list) r))])))

(unless (equal? (do-remove-letec 'a '[b c d a e f g h] eq?) '[b c d e f g h])
  (error 'do-remove "ouch"))


(unless (equal? (do-remove-callcc 'a '[b c d a e f g h] eq?) '[b c d e f g h])
  (error 'do-remove "ouch"))

(unless (equal? (do-remove-eq 'a '[b c d a e f g h] eq?) '[b c d e f g h])
  (error 'do-remove "ouch"))


(define LIMIT (inexact->exact (string->number (vector-ref (current-command-line-arguments) 0))))
(displayln LIMIT)

(module+ main
  
  'letec
  (tester do-remove-letec)

  'callcc
  (tester do-remove-callcc)

  'eq
  (tester do-remove-eq))
```

run with this bash script 

```
#!/bin/bash

raco make remove-test.rkt

for i in $(seq 1000000 1000000 20000000)
do
    echo "---------------------------------"
    echo $i
    racket remove-test.rkt $i
done
```

yields 

```
---------------------------------
1e+06
1000000
'letec
cpu time: 1247 real time: 1256 gc time: 949
'callcc
cpu time: 1183 real time: 1194 gc time: 917
'eq
cpu time: 1244 real time: 1262 gc time: 955
---------------------------------
2e+06
2000000
'letec
cpu time: 2641 real time: 2665 gc time: 2099
'callcc
cpu time: 3175 real time: 3225 gc time: 2539
'eq
cpu time: 2969 real time: 2993 gc time: 2380
---------------------------------
3e+06
3000000
'letec
cpu time: 5376 real time: 5418 gc time: 4391
'callcc
cpu time: 5967 real time: 6013 gc time: 4881
'eq
cpu time: 5675 real time: 5717 gc time: 4652
---------------------------------
4e+06
4000000
'letec
cpu time: 8049 real time: 8099 gc time: 6597
'callcc
cpu time: 8074 real time: 8119 gc time: 6557
'eq
cpu time: 8133 real time: 8181 gc time: 6652
---------------------------------
5e+06
5000000
'letec
cpu time: 12288 real time: 12372 gc time: 10303
'callcc
cpu time: 12789 real time: 12870 gc time: 10637
'eq
cpu time: 12397 real time: 12474 gc time: 10410
---------------------------------
6e+06
6000000
'letec
cpu time: 15419 real time: 15522 gc time: 12855
'callcc
cpu time: 16044 real time: 16153 gc time: 13485
'eq
cpu time: 15716 real time: 15837 gc time: 13061
---------------------------------
7e+06
7000000
'letec
cpu time: 19168 real time: 19278 gc time: 16047
'callcc
cpu time: 18240 real time: 18359 gc time: 15188
'eq
cpu time: 17734 real time: 17874 gc time: 14864
---------------------------------
8e+06
8000000
'letec
cpu time: 20736 real time: 21089 gc time: 17659
'callcc
cpu time: 19932 real time: 20036 gc time: 16649
'eq
cpu time: 20281 real time: 20422 gc time: 16869
---------------------------------
9e+06
9000000
'letec
cpu time: 23851 real time: 23964 gc time: 19922
'callcc
cpu time: 22874 real time: 22988 gc time: 18995
'eq
cpu time: 23033 real time: 23174 gc time: 19165
---------------------------------
1e+07
10000000
'letec
cpu time: 26937 real time: 27104 gc time: 22614
'callcc
cpu time: 28170 real time: 28351 gc time: 23693
'eq
cpu time: 27893 real time: 28057 gc time: 23249
---------------------------------
1.1e+07
11000000
'letec
cpu time: 25281 real time: 25443 gc time: 20542
'callcc
cpu time: 24761 real time: 24906 gc time: 19980
'eq
cpu time: 25112 real time: 25268 gc time: 20321
---------------------------------
1.2e+07
12000000
'letec
cpu time: 33661 real time: 33992 gc time: 28264
'callcc
cpu time: 32274 real time: 32429 gc time: 27186
'eq
cpu time: 32227 real time: 32509 gc time: 27244
---------------------------------
1.3e+07
13000000
'letec
cpu time: 34339 real time: 34498 gc time: 28866
'callcc
cpu time: 34208 real time: 34355 gc time: 28654
'eq
cpu time: 34808 real time: 34973 gc time: 29230
---------------------------------
1.4e+07
14000000
'letec
cpu time: 39605 real time: 39783 gc time: 33334
'callcc
cpu time: 37683 real time: 37939 gc time: 31711
'eq
cpu time: 39443 real time: 39644 gc time: 33063
---------------------------------
1.5e+07
15000000
'letec
cpu time: 41967 real time: 42159 gc time: 35484
'callcc
cpu time: 41100 real time: 41280 gc time: 34771
'eq
cpu time: 41056 real time: 41240 gc time: 34668
---------------------------------
1.6e+07
16000000
'letec
cpu time: 44629 real time: 44810 gc time: 37262
'callcc
cpu time: 44486 real time: 44671 gc time: 37144
'eq
cpu time: 44492 real time: 44685 gc time: 37140
---------------------------------
1.7e+07
17000000
'letec
cpu time: 48474 real time: 48672 gc time: 40871
'callcc
cpu time: 48340 real time: 48534 gc time: 40774
'eq
cpu time: 48285 real time: 48507 gc time: 40895
---------------------------------
1.8e+07
18000000
'letec
cpu time: 50447 real time: 50676 gc time: 42600
'callcc
cpu time: 48604 real time: 48855 gc time: 41076
'eq
cpu time: 48445 real time: 48726 gc time: 40903
---------------------------------
1.9e+07
19000000
'letec
cpu time: 53434 real time: 53636 gc time: 45023
'callcc
cpu time: 53133 real time: 53400 gc time: 44783
'eq
cpu time: 60587 real time: 60968 gc time: 51309
---------------------------------
2e+07
20000000
'letec
cpu time: 57636 real time: 58036 gc time: 49616
'callcc
cpu time: 58922 real time: 59300 gc time: 50749
'eq
cpu time: 61746 real time: 62111 gc time: 53263
```

This suggests to me: 

1. the continuation version doesn't pay much compared to the eq? version but eventually wins (very long lists of numbers)
2. the let/ec vs the let/cc version are also about the same.

**Comment by mflatt** [comment]
@mfelleisen I think your `tester` macro meant to use `do-remove` and not `do-remove-letec`. I also recommend lifting the list creation out of the loop and before the garbage collections, so you're more timing the remove operation.

I think you're right that `call/cc` will sometimes win for large lists, but there are complicating factors when a lot of memory is involved. On my machine, for example, 'callcc is faster than 'eq for 1e5, but it flips back around for 1e6.

**Pull request merged**
