### PR TITLE
make sure git checkouts have correct file perms

### PR DESCRIPTION
**Pull request by florence**
This fixes and issue where package installs sometimes have the wrong permissions a file.

I don't quite know how to tests this. I did check locally on the package that was having issues (https://github.com/rpless/cover-coveralls)

### CODE REVIEW

**Comment by rfindler** [comment]
Would you test this by having a canned git repo somewhere and then asking
this to do a checkout?

Is there already a test suite for this code?

**Comment by florence** [comment]
A grep of the main repo shows no usages of `git-checkout` in a test directory (or in fact out side of the pkg collection), so I don't think there is a test suite yet.

**Comment by mflatt** [comment]
My "test" originally was to clone the Racket repo and diff the result. I think that created the illusion of a test, so that I forgot to automate it.

**Comment by florence** [comment]
I've just done the same "test" as Matthew, and everything checks out. I don't think I'll have time to actually automate that test before racket con, and `cover-coveralls` is not working without this. Is it okay to merge it anyways?

**Comment by mflatt** [comment]
That's fine with me.

**Comment by rfindler** [comment]
Looks like something goes wrong on windows. From the AppVeyor build (above)

```
Downloading repository git://github.com/racket/data/?path=data-lib
file-or-directory-permissions: update failed due to unsupported bit combination
  path: C:\Users\appveyor\AppData\Local\Temp\1\14422706421442270642484-racket_data_master\.gitignore
  permission value: 420 
  context...:
   C:\projects\racket\racket\collects\net\git-checkout.rkt:669:5: loop 
   C:\projects\racket\racket\collects\net\git-checkout.rkt:141:11 
   C:\projects\racket\racket\collects\net\git-checkout.rkt:38:2: retry-loop 
   C:\projects\racket\racket\collects\pkg\private\download.rkt:99:2: download! 
   C:\projects\racket\racket\collects\file\cache.rkt:63:2: fetch-and-continue 
   C:\projects\racket\racket\collects\racket\contract\private\arrow-val-first.rkt:324:3 
   C:\projects\racket\racket\collects\pkg\private\download.rkt:91:0: download-repo!24 
   C:\projects\racket\racket\collects\pkg\private\stage.rkt:299:11 
   C:\projects\racket\racket\collects\pkg\private\stage.rkt:106:0: stage-package/info46 
   C:\projects\racket\racket\collects\pkg\private\stage.rkt:106:0: stage-package/info46 
   C:\projects\racket\racket\collects\pkg\private\install.rkt:641:4: for-loop 
   C:\projects\racket\racket\collects\pkg\private\install.rkt:141:0: install-packages74 
   C:\projects\racket\racket\collects\pkg\private\..:261:28 
   C:\projects\racket\racket\collects\racket\contract\private\arrow-val-first.rkt:324:3 
   C:\projects\racket\racket\collects\racket\file.rkt:374:8 
   C:\projects\racket\racket\collects\racket\file.rkt:363:0: call-with-file-lock42 
   ... 
NMAKE : fatal error U1077: 'racket\racket.EXE' : return code '0x1'
Stop.
```

**Comment by rfindler** [comment]
I pushed the commits, but then reverted them when I realized the issue above. Sorry about the churn.

**Comment by florence** [comment]
As it turns out, `644` is not a valid set of permissions on windows. My google fu tells me that `git` handles this by converting every file to `755` on windows, so I changed things to do that. I have no local windows installs to I'm letting the automatic appveyor build do that.

**Comment by florence** [comment]
Hrm, doesn't look like the appveyor build here does any kind of `raco pkg install`. Does anyone have a windows machine I can test this on?

**Comment by samth** [comment]
It installs a number of packages for testing -- that's why it failed.

**Comment by florence** [comment]
Oh I see, around line 2201 of the output. Missed that. I guess that means its fixed, now that the appveyor build is passing?

**Comment by samth** [comment]
Yeah, looks good.

**Comment by rfindler** [comment]
Okay if I squash the commits?

**Comment by rfindler** [comment]
I've pushed https://github.com/racket/racket/commit/35a0f0c71c6a53a0cb09520ef9de335cb06e66d4

**Comment by florence** [comment]
This seems to have caused a failure on a different appveyor build: https://ci.appveyor.com/project/plt/racket/build/1.0.785

@mflatt Am I missunderstanding the code in file_or_dir_permissions? I thought `755` was valid because the read and write were set for every level of permissions?

**Comment by mflatt** [comment]
@florence write needs to be the same across all levels, and read and exec always need to be set; so, I think that means the valid permissions are 777 and 555.

**Comment by mflatt** [comment]
Maybe the right strategy is just to not try to set permissions on Windows

**Comment by samth** [comment]
Do we know what git itself does?

**Comment by rfindler** [comment]
Spencer suggests reverting this commit, but I think a better intermediate
state is one that just doesn't make these changes on windows. Is that okay
with everyone?

**Comment by samth** [comment]
Seems sensible to me.

**Pull request closed without merging**
