### PR TITLE
add #:newline? argument to pretty-printing functions

### PR DESCRIPTION
**Pull request by AlexKnauth**
Versions of pretty-print, pretty-write, and pretty-display that don’t print extra newlines at the end.

### CODE REVIEW

**Comment by samth** [comment]
I think a keyword argument might be nicer here.

**Comment by mflatt** [comment]
I was about to write the same as @samth...

**Comment by AlexKnauth** [comment]
Ok done.

**Comment by mflatt** [comment]
@AlexKnauth You seem to have added a keyword argument internally, but what I meant (and what I thought Sam meant) was to add an optional `#:newline?` argument to `pretty-print` instead of introducing the name `pretty-print/no-inline`, etc.

**Comment by AlexKnauth** [comment]
Oh, okay, I'll do that then.

**Comment by AlexKnauth** [comment]
I've updated this to add optional `#:newline?` keyword arguments to `pretty-print`, `pretty-write`, and `pretty-display`. I'll add documentation once the `make` is done.

**Comment by rfindler** [comment]
Maybe in the docs point out that passing `#t` means that `printing-port-print-line` isn't called with `#f` any more?

**Comment by AlexKnauth** [comment]
What do you mean? It isn't being called at all, in my current code...

**Comment by AlexKnauth** [comment]
I see what you mean, okay.

**Comment by rfindler** [comment]
Yeah: I just mean that in addition to the high-elvel description of the new argument, also include the technical note as to how it changes which callbacks are called back.

Thanks for this, btw.

**Comment by AlexKnauth** [comment]
Does that documentation look good?

It's a bit weird because the `#:newline?` argument determines whether `pretty-print-print-line` is called, but `pretty-print-print-line` doesn't always print a newline. I'm not sure what to do about that though.

**Comment by rfindler** [comment]
Generally these functions don't accept booleans, but accept `any/c` and treat non-`#f` values as true (eg `pretty-print-show-inexactness`).

I think the convention for documenting such things is to write "a true value" and "@racket[#f]", but I see a few other places in those docs where that convention is violated.

The sentence "If it is supplied with false, the @racket[pretty-print-print-line] callback is not called." doesn't seem right. I think it is just not called with `#f` anymore, but it is still called on all the other line breaks.

Also the second paragraph of `pretty-print-print-line`'s docs needs adjusting.

**Comment by AlexKnauth** [comment]
I meant that it's not called for the last newline, which the previous sentence mentions, but you're right, it's not clear.

**Comment by AlexKnauth** [comment]
I've modified it to clarify that if `newline?` is supplied with false, the `pretty-print-print-line` callback is not called after the printed value. I don't want to confuse people by saying "not called with false".

**Comment by rfindler** [comment]
That is better, I agree.

**Comment by AlexKnauth** [comment]
Logically, it's good to think of it as a boolean, and if we ever want to put a third setting in there, like `'just-internal` or `'just-end`, it might be better to document it as a boolean for now.

**Comment by rfindler** [comment]
In that case,  you'll want to add a check?

**Comment by AlexKnauth** [comment]
Okay, I've added the check

**Comment by AlexKnauth** [comment]
Does this look good now?

**Comment by rfindler** [comment]
Commits 1bfa0c5292679ec66271839417eb5afb8b1c7098 and
203dbf78d9deb3999a8eea236410b55a6d8f4456 look good to me, except that I
don't see any test suites. I didn't look over the others.

Robby

**Comment by AlexKnauth** [comment]
Oh, right. Where are the pretty-printing tests?

**Comment by rfindler** [comment]
Grep suggests pkgs/racket-test-core/tests/racket/pretty.rktl.

**Comment by rfindler** [comment]
Tests look good to me.

**Comment by AlexKnauth** [comment]
For some reason they error on my machine
```
Section(namespaces)
Section(collects)
Section(modprot)
ERROR: UNKNOWN::79: read (compiled): ill-formed code [../../../racket/gc2/../src/read.c:5585]
```
But they're passing on Appveyor and Travis

**Comment by AlexKnauth** [comment]
It's possible that something weird is happening with my compiled files, since I've been working with both a snapshot version a few weeks old and the git HEAD version. So should this be merged?

**Comment by rfindler** [comment]
It is okay with me to push those three commits (although do you see a
reason not to squash them?). Do you want me to do it?

**Comment by AlexKnauth** [comment]
I don't have push access. So this shouldn't include the re-formatting stuff?

**Comment by rfindler** [comment]
I didn't check over the formatting stuff. I can see how, tho, in this case my usual objections to formatting changes don't apply (this is old code that is almost never touched so the lost 'git blame' information is minor compared to the readability).

**Comment by rfindler** [comment]
Thanks, I've pushed the commits (except that I combined the three commits that were all pieces of the same change)

**Pull request closed without merging**
