### PR TITLE
Check ADLER32 after inflate

### PR DESCRIPTION
**Pull request by lehitoskin**
After prompting from @tonyg I decided to add an ADLER32 check in `zlib-inflate`.

### CODE REVIEW

**Comment by tonyg** [comment]
(By the way, @lehitoskin, thank you for making the PR!)

**Comment by tonyg** [comment]
Sure enough, the failing CI builds are from not having an `open-output-bytes` port in `o`.

**Comment by lehitoskin** [comment]
I added an intermediate string port. Should be fine now.

**Comment by lehitoskin** [comment]
It appears the appveyor check failed because of a networking issue:
```
Section(foreign)
Section(cstruct)
Section(uni-norm)
ERROR: tcp-connect: connection failed
  address: www.unicode.org
  port number: 80
  step: 6
  system error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.; errno=10060
Command exited with code 2
```
And I don't know quite why that one build failed in Travis. I looked around in the logs and it doesn't appear to be related to my code changes.

**Comment by lehitoskin** [comment]
The error in Travis for the one test doesn't really make sense to me, either: https://travis-ci.org/racket/racket/jobs/191791547#L1648-L1671

**Comment by samth** [comment]
@tonyg Is your review comment addressed?

**Comment by samth** [comment]
@lehitoskin can you rebase this, so that the CI runs again?

**Comment by lehitoskin** [comment]
@samth Okay. I hope I did this correctly...

**Comment by samth** [comment]
@mflatt any thoughts on this PR?

**Comment by mflatt** [comment]
Do we care that this keeps a copy of a potentially large file in memory, instead of always streaming to an output file? Probably we don't deal with any files big enough for this to matter, so I'm ok with ignoring that issue for now, but but the alternative would be a thread that performs the checksum concurrently.

**Comment by samth** [comment]
That was my worry as well here. I think we probably want to avoid decompressing the whole thing in memory.

**Comment by mflatt** [comment]
I'll merge and adjust the implementation to streaming

**Pull request merged**
