### PR TITLE
Generate new certificate for testing using 2048bits

### LINKED ISSUE #2748: ssl-load-certificate-chain! misbehaves in debian:stable-slim
I noticed due to some CI testing experiments that the function `ssl-load-certificate-chain!` doesn't like our `test.pem` on `debian:stable-slim`. All good in `ubuntu:18.04` though.

In debian you get:
```
# raco test -l tests/net/url-port
raco test: (submod "/root/.racket/7.4.0.1/pkgs/net-test/tests/net/url-port.rkt" test)
raco test: @(test-responsible 'jay)
test: 1/1502 test failures:
/root/.racket/7.4.0.1/pkgs/net-test/tests/net/url-port.rkt:156:3: test failure in (for ((i 100)) (run-tests "https" (let ((ctx (ssl-make-server-context))) (ssl-load-certificate-chain! ctx (collection-file-path "test.pem" "openssl")) (ssl-load-private-key! ctx (collection-file-path "test.pem" "openssl")) (lambda (in out) (ports->ssl-p...
  expected: non-#f single value
       got: error: ssl-load-certificate-chain!: load failed from: #<path:/root/racket/racket/collects/openssl/test.pem> (error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small)
  context...:
   (submod "/root/.racket/7.4.0.1/pkgs/net-test/tests/net/url-port.rkt" main): [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   /root/.racket/7.4.0.1/pkgs/compiler-lib/compiler/commands/test.rkt:179:16
url-port.rkt: raco test: test raised an exception
1/1503 test failures
```

If you check the package versions, in ubuntu and debian they look like basically the same with the exception of distro specific patches.
ubuntu:
```
# dpkg -s openssl
Package: openssl
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 1223
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1.1.1-1ubuntu2.1~18.04.4
Depends: libc6 (>= 2.15), libssl1.1 (>= 1.1.1)
Suggests: ca-certificates
Conffiles:
 /etc/ssl/openssl.cnf 61c17536f212862b4101ca83ae199157
Description: Secure Sockets Layer toolkit - cryptographic utility
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains the general-purpose command line binary /usr/bin/openssl,
 useful for cryptographic operations such as:
  * creating RSA, DH, and DSA key parameters;
  * creating X.509 certificates, CSRs, and CRLs;
  * calculating message digests;
  * encrypting and decrypting with ciphers;
  * testing SSL/TLS clients and servers;
  * handling S/MIME signed or encrypted mail.
Homepage: https://www.openssl.org/
Original-Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
```

debian:
```
# dpkg -s openssl
Package: openssl
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 1458
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 1.1.1c-1
Depends: libc6 (>= 2.15), libssl1.1 (>= 1.1.1)
Suggests: ca-certificates
Conffiles:
 /etc/ssl/openssl.cnf 8dd4de5642570c91e9071900b6b9d5bc
Description: Secure Sockets Layer toolkit - cryptographic utility
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains the general-purpose command line binary /usr/bin/openssl,
 useful for cryptographic operations such as:
  * creating RSA, DH, and DSA key parameters;
  * creating X.509 certificates, CSRs, and CRLs;
  * calculating message digests;
  * encrypting and decrypting with ciphers;
  * testing SSL/TLS clients and servers;
  * handling S/MIME signed or encrypted mail.
Homepage: https://www.openssl.org/
```

### PR DESCRIPTION
**Pull request by pmatos**
Fixes #2748

Steps to create this certificate:
openssl genrsa -out key.pem 2048
openssl req -new -sha256 -key key.pem -out csr.csr
openssl req -x509 -sha256 -key key.pem -in csr.csr -out certificate.pem
cat key.pem certificate.pem > test.pem

### CODE REVIEW

**Comment by rmculpepper** [comment]
Thanks for doing this. The default validity duration seems to be very short. Since this is only for testing, let's make a long-lived certificate (like 5 or 10 years). Check the validity period with `openssl x509 -text -in certificate.pem`.

**Comment by pmatos** [comment]
@rmculpepper thanks. Force pushed new certificate valid for 10yrs. Hope to be the one having to reissue it by then. (-:

**Comment by pmatos** [comment]
ping!

**Comment by rmculpepper** [comment]
One more issue: running `raco test -c tests/openssl` shows a failure in `test-server-sni.rkt`, which depends on the Subject Common Name (CN) in the `openssl/test.pem` certificate. That test should probably be rewritten at some point to make it self-contained, but it would probably be simpler for now to just use the same Subject info from the old certificate.

**Comment by pmatos** [comment]
Oh, sorry. I was running `raco test -l tests/openssl/basic` and didn't catch that one.

**Comment by pmatos** [comment]
@rmculpepper looks ok now, what do you think?

**Comment by rmculpepper** [comment]
That's all I can think of. I'll merge, and if there's anything else DrDr can tell us. Thanks!

**Comment by pmatos** [comment]
Thanks.

**Pull request merged**
