### PR TITLE
Rename define-simple-macro to define-syntax-parse-rule

### PR DESCRIPTION
**Pull request by sorawee**
This PR is based on @lexi-lambda's #1310.
It resolves the conflicts in the mentioned PR and
adjusts the version so that it's up-to-date.

Closes #1310

### CODE REVIEW

**Comment by sorawee** [comment]
Can we merge this for v8.0?

**Comment by samth** [comment]
I think we need @rmculpepper's thoughts here.

**Comment by rmculpepper** [comment]
I'm ambivalent. In my view, this replaces one okay-but-not-great name with another okay-but-not-great name. On the other hand, other people seem to like this new name better. So if people really think this is an improvement, then I'm willing to go along with the name change.

**Comment by jackfirth** [comment]
I think this is a solid improvement. I agree that the new name is okay-but-not-great, but I think the current name is _really_ bad, to the point where it makes the API come off as untrustworthy. So I'd really like to see this merged in for 8.0. I think @rmculpepper should be the final decider on whether this get merged, so I'll assign it to him.

**Comment by Metaxal** [comment]
IMHO,
Pros:
* consistent name (big pro). 

Cons:
* there's no `syntax-parse-rules` (by analogy to `syntax-rules`), only `syntax-parse`. So not fully consistent either.
* pretty long name, not a good selling point for making something the default.
* not very informative either.  Imagine you come to Racket, and you've heard about its powerful macro system. The first thing you're told to learn is `define-syntax-parse-rule`. "Uh, what the heck does that even mean?" You can't even tell how the words should be grouped: is it (define-syntax)-(parse-rule) or define-(syntax-parse)-rule? That's a real put-off. By contrast `define-simple-macro` is very friendly, despite its naming inconsistency.

**Pull request merged**
