### PR TITLE
contract: two small changes

### PR DESCRIPTION
**Pull request by bennn**
- move a comment
- simplify a helper function

### CODE REVIEW

**Comment by rfindler** [comment]
Should `fast-append` just check `l2` and, if it isn't null, simply call `append`?

**Comment by rfindler** [comment]
Also, if I'm not mistaken, the change you made is one that the optimizer will undo, turning the code back into the version that takes two arguments.

**Comment by rfindler** [comment]
(well, maybe not chez)

**Comment by bennn** [comment]
Calling `append` would definitely be easier to read

**Pull request merged**
