### PR TITLE
fasl: find shared values in hash tables.

### PR DESCRIPTION
**Pull request by samth**
Also, add test to check sharing of uninterned symbols.

### CODE REVIEW

**Comment by samth** [comment]
@mflatt Despit the comment at the top of this loop, we need this to be able to reliably round-trip the result of expansion in Pycket, since the expander uses uninterned symbols.

**Comment by mflatt** [comment]
This seems like a good change. But does the expander use uninterned symbols where it should use unreadable symbols?

**Comment by samth** [comment]
The use of uninterned symbols is in expand/env.rkt. I'm not sure what the reasons to choose between them is, so I can't be sure if one is better here.

**Comment by mflatt** [comment]
Ah, yes, that needs to be uninterned. Thanks for the explanation.

**Pull request merged**
