### PR TITLE
scalinger -> scaliger

### PR DESCRIPTION
**Pull request by harrisi**
This fixes racket/racket#757. Tests are included for both versions,
and documentation now only references the new, correctly named,
procedures.

### CODE REVIEW

**Comment by samth** [comment]
I think the primary implementation should have the fixed name, so that error messages and printouts have the right name.

**Comment by harrisi** [comment]
Maybe I'm misunderstanding, but this does have that behavior, doesn't it?

```
> (julian/scalinger->string '())
julian/scalinger->string: contract violation
  expected: exact-integer?
  given: '()
  in: the 1st argument of
      (-> exact-integer? string?)
  contract from: <collects>/racket/date.rkt
  blaming: top-level
   (assuming the contract is correct)
  at: <collects>/racket/date.rkt:22.2
  context...:
   /Users/ian/dev/racket/racket/collects/racket/contract/private/blame.rkt:156:0: raise-blame-error16
   /Users/ian/dev/racket/racket/collects/racket/contract/private/arrow-val-first.rkt:363:18
   /Users/ian/dev/racket/racket/collects/racket/private/misc.rkt:87:7
> (julian/scaliger->string '())
julian/scaliger->string: contract violation
  expected: exact-integer?
  given: '()
  in: the 1st argument of
      (-> exact-integer? string?)
  contract from: <collects>/racket/date.rkt
  blaming: top-level
   (assuming the contract is correct)
  at: <collects>/racket/date.rkt:23.2
  context...:
   /Users/ian/dev/racket/racket/collects/racket/contract/private/blame.rkt:156:0: raise-blame-error16
   /Users/ian/dev/racket/racket/collects/racket/contract/private/arrow-val-first.rkt:363:18
   /Users/ian/dev/racket/racket/collects/racket/private/misc.rkt:87:7
>
```

**Comment by harrisi** [comment]
Also, sorry about the merge being added to this pull request. I don't know what can be done about that. I really am a lot worse with git than I realized.

**Comment by samth** [comment]
Ah, the contract changes the name of the procedure, so my worry is moot.

**Comment by stamourv** [comment]
Merged, thanks!

**Pull request closed without merging**
