### PR TITLE
Remove gitlab CI

### PR DESCRIPTION
**Pull request by pmatos**
After #3159 is merged, gitlab CI files can be removed.

### CODE REVIEW

**Comment by pmatos** [comment]
I am wondering if moving the docker images for `racket/racket-ci` is going to cause problems with DockerHub builds...

**Comment by samth** [comment]
Yes but it should be easy to change.

**Comment by samth** [comment]
I wonder if the Docker images should go in the racket-ci repo. They don't need to rebuild on every racket commit.

**Comment by pmatos** [comment]
> I wonder if the Docker images should go in the racket-ci repo. They don't need to rebuild on every racket commit.

Unsure we can do that from docker but from Actions we could have a workflow to rebuild and push the images only when the dockerfiles change. Would you like me to add a PR to do that?

**Pull request merged**
