### PR TITLE
Disable will section test with jit disabled

### PR DESCRIPTION
**Pull request by pmatos**
Related to #2963

### CODE REVIEW

**Comment by pmatos** [comment]
Would it be ok to disable this to fix #2963 or do you have another suggestion?

**Comment by mflatt** [comment]
I'm looking into this, because I don't see a reason that it should fail with 3m. But I also haven't been able to trigger a failure on my machine, yet.

**Comment by pmatos** [comment]
You might need a slower machine. I have one around. Will try it tomorrow if you don't sort it out in the meantime.

**Comment by mflatt** [comment]
I think I understand now. It's a question of the cost of non-tail recursion, which is higher without the JIT. I'll adjust the test.

**Comment by pmatos** [comment]
Closing without merging as 58f51f15eddfe41f4a6c17630091441230fa93ac is a better fix by @mflatt

**Pull request closed without merging**
