### PR TITLE
Unsafe hash iterate

### PR DESCRIPTION
**Pull request by stchang**
This pull request is not complete but I wanted to get feedback on whether it is worthwhile before proceeding.

@samth and I were discussing how there is no `in-list`-like fast path for `in-set` and `in-hash` when used in `for` clauses.

It seems something like this would be very useful but is there any reason why it's a bad idea?

Preliminary microbenchmarks with `in-immutable-hash-keys` from this pr, using unsafe hash ops I added, show ~20% performance improvement. And that is without jit inlining.

### CODE REVIEW

**Comment by samth** [comment]
We can implement `in-hash` using `hash-iterate-keys` and `hash-ref`, without needing any unsafe code, right?

**Comment by stchang** [comment]
Yes but it does not improve things

**Comment by stchang** [comment]
Partially because hash-iterate- still needs to check three different representations

**Comment by stchang** [comment]
For mutable hashes, there is more speedup because they are easier to iterate, ~65%.

**Comment by stchang** [comment]
> We can implement in-hash using hash-iterate-keys and hash-ref, without needing any unsafe code, right?

On second look, just using `hash-iterate-` does provide some improvement. I'll submit a separate PR with that change while I look into add unsafe versions.

**Comment by stchang** [comment]
Anyone object to doing unsafe hash iteration in for loops?

**Comment by stchang** [comment]
Here are some microbenchmarks:

```
$ racket for-benchmarking.rkt
first number: current Racket (no for loop fast path)
second number: (safe) fast path
third number: unsafe fast path
immutable --------------------
in-hash
cpu time: 396 real time: 395 gc time: 0
cpu time: 352 real time: 355 gc time: 0
cpu time: 192 real time: 192 gc time: 0
in-hash-pairs
cpu time: 376 real time: 377 gc time: 0
cpu time: 356 real time: 355 gc time: 0
cpu time: 188 real time: 188 gc time: 0
in-hash-keys
cpu time: 220 real time: 223 gc time: 0
cpu time: 200 real time: 200 gc time: 0
cpu time: 188 real time: 188 gc time: 0
in-hash-values
cpu time: 224 real time: 223 gc time: 0
cpu time: 200 real time: 201 gc time: 0
cpu time: 184 real time: 183 gc time: 0
mutable --------------------
in-hash
cpu time: 96 real time: 98 gc time: 0
cpu time: 52 real time: 53 gc time: 0
cpu time: 28 real time: 26 gc time: 0
in-hash-pairs
cpu time: 80 real time: 80 gc time: 0
cpu time: 56 real time: 58 gc time: 0
cpu time: 28 real time: 26 gc time: 0
in-hash-keys
cpu time: 64 real time: 64 gc time: 0
cpu time: 40 real time: 40 gc time: 0
cpu time: 20 real time: 22 gc time: 0
in-hash-values
cpu time: 64 real time: 64 gc time: 0
cpu time: 36 real time: 38 gc time: 0
cpu time: 28 real time: 26 gc time: 0
weak --------------------
in-hash
cpu time: 164 real time: 164 gc time: 0
cpu time: 112 real time: 114 gc time: 0
cpu time: 64 real time: 61 gc time: 0
in-hash-pairs
cpu time: 152 real time: 153 gc time: 0
cpu time: 104 real time: 107 gc time: 0
cpu time: 64 real time: 61 gc time: 0
in-hash-keys
cpu time: 136 real time: 137 gc time: 0
cpu time: 84 real time: 85 gc time: 0
cpu time: 64 real time: 62 gc time: 0
in-hash-values
cpu time: 108 real time: 110 gc time: 0
cpu time: 76 real time: 78 gc time: 0
cpu time: 52 real time: 50 gc time: 0
```

**Comment by stchang** [comment]
This is still without inlining (mostly --- I added it for mutable hash keys and values).

**Comment by stchang** [comment]
Here is the test file:

```
#lang racket
(define big-list (build-list 1000000 add1))
(define big-list2 (build-list 1000000 values))

(define big-hash/immut (make-immutable-hash (map cons big-list big-list2)))
(define big-hash/mut (make-hash (map cons big-list big-list2)))
(define big-hash/weak (make-weak-hash (map cons big-list big-list2)))

(define big-hash/immut/seq (in-hash big-hash/immut))
(define big-hash/mut/seq (in-hash big-hash/mut))
(define big-hash/weak/seq (in-hash big-hash/weak))

(define big-hash/immut-pairs/seq (in-hash-pairs big-hash/immut))
(define big-hash/mut-pairs/seq (in-hash-pairs big-hash/mut))
(define big-hash/weak-pairs/seq (in-hash-pairs big-hash/weak))

(define big-hash/immut-keys/seq (in-hash-keys big-hash/immut))
(define big-hash/mut-keys/seq (in-hash-keys big-hash/mut))
(define big-hash/weak-keys/seq (in-hash-keys big-hash/weak))

(define big-hash/immut-vals/seq (in-hash-values big-hash/immut))
(define big-hash/mut-vals/seq (in-hash-values big-hash/mut))
(define big-hash/weak-vals/seq (in-hash-values big-hash/weak))

(collect-garbage)
(collect-garbage)
(collect-garbage)

(displayln "first number: current Racket (no for loop fast path)")
(displayln "second number: (safe) fast path")
(displayln "third number: unsafe fast path")
(require rackunit)

(displayln "immutable --------------------")
(displayln "in-hash")
(check-true 
  (= (time (for/sum ([(k v) big-hash/immut/seq]) k))
     (time (for/sum ([(k v) (in-hash big-hash/immut)]) k))
     (time (for/sum ([(k v) (in-immutable-hash big-hash/immut)]) k))))
(displayln "in-hash-pairs")
(check-true 
  (= (time (for/sum ([k+v big-hash/immut-pairs/seq]) (car k+v)))
     (time (for/sum ([k+v (in-hash-pairs big-hash/immut)]) (car k+v)))
     (time (for/sum ([k+v (in-immutable-hash-pairs big-hash/immut)]) 
             (car k+v)))))
(displayln "in-hash-keys")
(check-true
  (= (time (for/sum ([k big-hash/immut-keys/seq]) k))
     (time (for/sum ([k (in-hash-keys big-hash/immut)]) k))
     (time (for/sum ([k (in-immutable-hash-keys big-hash/immut)]) k))))
(displayln "in-hash-values")
(check-true
  (= (time (for/sum ([v big-hash/immut-vals/seq]) v))
     (time (for/sum ([v (in-hash-values big-hash/immut)]) v))
     (time (for/sum ([v (in-immutable-hash-values big-hash/immut)]) v))))

(displayln "mutable --------------------")
(displayln "in-hash")
(check-true
  (= (time (for/sum ([(k v) big-hash/mut/seq]) k))
     (time (for/sum ([(k v) (in-hash big-hash/mut)]) k))
     (time (for/sum ([(k v) (in-mutable-hash big-hash/mut)]) k))))
(displayln "in-hash-pairs")
(check-true
  (= (time (for/sum ([k+v big-hash/mut-pairs/seq]) (car k+v)))
     (time (for/sum ([k+v (in-hash-pairs big-hash/mut)]) (car k+v)))
     (time (for/sum ([k+v (in-mutable-hash-pairs big-hash/mut)]) (car k+v)))))
(displayln "in-hash-keys")
(check-true
  (= (time (for/sum ([k big-hash/mut-keys/seq]) k))
     (time (for/sum ([k (in-hash-keys big-hash/mut)]) k))
     (time (for/sum ([k (in-mutable-hash-keys big-hash/mut)]) k))))
(displayln "in-hash-values")
(check-true
  (= (time (for/sum ([v big-hash/mut-vals/seq]) v))
     (time (for/sum ([v (in-hash-values big-hash/mut)]) v))
     (time (for/sum ([k (in-mutable-hash-values big-hash/mut)]) k))))

(displayln "weak --------------------")
(displayln "in-hash")
(check-true
  (= (time (for/sum ([(k v) big-hash/weak/seq]) k))
     (time (for/sum ([(k v) (in-hash big-hash/weak)]) k))
     (time (for/sum ([(k v) (in-weak-hash big-hash/weak)]) k))))
(displayln "in-hash-pairs")
(check-true
  (= (time (for/sum ([k+v big-hash/weak-pairs/seq]) (car k+v)))
     (time (for/sum ([k+v (in-hash-pairs big-hash/weak)]) (car k+v)))
     (time (for/sum ([k+v (in-weak-hash-pairs big-hash/weak)]) (car k+v)))))
(displayln "in-hash-keys")
(check-true
  (= (time (for/sum ([k big-hash/weak-keys/seq]) k))
     (time (for/sum ([k (in-hash-keys big-hash/weak)]) k))
     (time (for/sum ([k (in-weak-hash-keys big-hash/weak)]) k))))
(displayln "in-hash-values")
(check-true
  (= (time (for/sum ([v big-hash/weak-vals/seq]) v))
     (time (for/sum ([v (in-hash-values big-hash/weak)]) v))
     (time (for/sum ([v (in-weak-hash-values big-hash/weak)]) v))))
```

**Comment by stchang** [comment]
Realized that impersonators and chaperones don't work properly. Closing and trying again.

**Pull request closed without merging**
