### PR TITLE
syntax/parse: only parse syntax-class patterns once

### PR DESCRIPTION
**Pull request by rmculpepper**
See #2164.

### CODE REVIEW

**Comment by AlexKnauth** [comment]
I'm getting a bunch of errors that look like this:
```racket
?: bad syntax
  in: #s(pat:fixup k:id k k id #s(arguments () () ()) #f #f)
  compilation context...:
   .../turnstile/turnstile.rkt
   .../turnstile/lang.rkt
  context...:
   do-raise-syntax-error
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   loop
   for-loop
   finish-bodys
   for-loop
   finish-bodys
   do-local-expand56
   syntax-local-expand-expression33
   .../racket/private/stxparam.rkt:62:2: let-local-keys
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   for-loop
   ...
```

Commenting here because this PR introduced the "fixup" patterns.

**Comment by AlexKnauth** [comment]
Here's a minimal example:
```racket
#lang racket/base
(require syntax/parse)

(define-splicing-syntax-class props
  [pattern (~and (~seq stuff ...) (~seq k:id ...))])
```

**Comment by AlexKnauth** [comment]
The `[(pat:fixup _ _ _ _ _ _) #t]` clause on line 355 of `rep-patterns.rkt` has only six fields, where the struct is supposed to have seven.

**Comment by AlexKnauth** [comment]
The `?: bad syntax` error message looks like it's coming from a `syntax-case` expression.

The `syntax-case` expression on lines 540-717 of `parse.rkt` doesn't have clauses for `pat:fixup` or `pat:and/fixup`.
https://github.com/racket/racket/blob/master/racket/collects/syntax/parse/private/parse.rkt#L540-L717

The other `syntax-case` expressions in that file don't have clauses for that either. But since this error doesn't show up all the time, maybe the `fixup` patterns are supposed to be gone by then? Is it possible that the `(~and (~seq stuff ...) ...pat...)` is messing up the pass where it gets rid of the `fixup`s?

**Comment by rmculpepper** [comment]
@AlexKnauth, should be fixed now, thanks. Yes, the fixup patterns are supposed to be gone by the time parse:S gets involved.

**Comment by AlexKnauth** [comment]
Thank you!

**Pull request merged**
