### PR TITLE
fix typo, stream-empty? -> set-empty?

### PR DESCRIPTION
**Pull request by AlexKnauth**
This fixes a problem discovered by @pmatos on the [Racket Users mailing list](https://groups.google.com/forum/#!topic/racket-users/gpbEXO6KFek).

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Where should I put a regression test like this?
```racket
(define-syntax-rule (delegate method params input wrap-output)
  (begin
    (define/generic generic-method method)
    (define (method . params) (wrap-output (generic-method . input)))))

(struct mask (s)
  #:methods gen:set
  [(delegate set-empty?  [m]   [(mask-s m)]   identity)
   (delegate set-member? [m v] [(mask-s m) v] identity)
   (delegate set-add     [m v] [(mask-s m) v] mask)
   (delegate set-remove  [m v] [(mask-s m) v] mask)
   (delegate set-first   [m]   [(mask-s m)]   identity)
   (delegate set-rest    [m]   [(mask-s m)]   mask)])

;; ---

(check set=?
       (list 3 5 8)
       (stream->list (set->stream (mask (set 3 5 8)))))
```

**Comment by AlexKnauth** [comment]
I added the test in `pkgs/racket-test-extra/tests/racket/set-regression.rkt`.

**Comment by AlexKnauth** [comment]
Anyone have any thoughts on this? Is it okay to merge this small change?

**Comment by bennn** [comment]
go merge!

**Pull request merged**
