### PR TITLE
Mark other error functions as NORETURN

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Comment by pmatos** [comment]
This PR cuts about 48 false positives from the static analyser. 220 errors to go.

**Comment by mflatt** [comment]
The `NORETURN` annotations cause trouble with my compiler, because it can't verify that the annotation is correct. My attempt to avoid that problem in f14d7e06bba5886a0e41a801fa27a8faecde3e43 only worked for the CGC part of the build, and the code generated for 3m still confuses the compiler.

Could we make this annotation be a no-op unless is is specifically requested through a compiler flag like `-DMZ_DECLARE_NORETURN`?

**Comment by pmatos** [comment]
Sorry for the delay, a cold caught me by surprise and I was off a couple of days. Have a bit to catch up to. 

I agree with you that we should streamline this `NORETURN` thing. Still, one thing is killing me: curiosity. Which compiler are you using?

Give me a few days to look into this and I will get back to you with a better PR.

**Comment by samth** [comment]
This is also an issue for the 3m-generated code on drdr, as you can see here: http://drdr.racket-lang.org/51622/pkg-src/build/make#output1

That is unfortunately a very old gcc, 4.8.4 (that machine runs Ubuntu 14.0.4). If it would help, we could potentially upgrade the compiler, but @jeapostrophe would know more.

**Comment by mflatt** [comment]
I use the default compiler on Mac OS, which is Clang.

@pmatos  If the `-DMZ_DECLARE_NORETURN` approach is ok with you, I can add that today so that we fix the test failures.

**Comment by pmatos** [comment]
Apologies for the failures. Since it's urgent, let me work on it now. Give me a few minutes.

**Comment by pmatos** [comment]
I have added two commits here. Haven't tested them yet.

**Comment by pmatos** [comment]
The first one adds the `MZ_DECLARE_NORETURN` as suggested.

The second one removes the `exit(0)` you added previously as a workaround but it's really ugly so I removed it, if you don't mind. :)

**Comment by mflatt** [comment]
This is exactly what I would have done - thanks!

**Pull request merged**
