### PR TITLE
typographic rehash of `--help` output

### PR DESCRIPTION
**Pull request by Krasjet**
The current output for `--help` is quite messy and hard to
navigate.

I added some indentation and spacing to make the document
easier to read. For example,

    File and expression options:

      -e <exprs>, --eval <exprs>
         Evaluate <exprs>, print results
      -f <file>, --load <file>
         Like -e '(load "<file>")' without printing

The new layout is longer, but at least it is readable. It
might be better if we could move all the options to a man
page and only select a few common ones to put in `--help`.

Here is a comparison.

Before:

```console
$ gracket --help
gracket: [<option> ...] <argument> ...
 X configuration options (must precede all other options):
  -display <display>, -geometry <geometry>, -fn <font>, -font <font>,
  -bg <color>, -background <color>, -fg <color>, -foreground <color>,
  -iconic, -name <name>, -rv, -reverse, +rv, -selectionTimeout <timeout>,
  -synchronous, -title <title>, -xnllanguage <language>, -xrm <file>
 File and expression options:
  -e <exprs>, --eval <exprs> : Evaluate <exprs>, prints results
  -f <file>, --load <file> : Like -e '(load "<file>")' without printing
  -t <file>, --require <file> : Like -e '(require (file "<file>"))' [*]
  -l <path>, --lib <path> : Like -e '(require (lib "<path>"))' [*]
  -p <package> : Like -e '(require (planet "<package>")' [*]
  -r <file>, --script <file> : Same as -f <file> -N <file> --
  -u <file>, --require-script <file> : Same as -t <file> -N <file> --
  -k <n> <m> <p> : Load executable-embedded code from offset <n> to <p>
  -m, --main : Call `main' with command-line arguments, print results
  [*] Also `require's a `main' submodule, if any
 Interaction options:
  -i, --repl : Run interactive read-eval-print loop; implies -v
  -n, --no-lib : Skip `(require (lib "<init-lib>"))' for -i/-e/-f/-r
  -v, --version : Show version
  -K, --back : Don't bring application to the foreground (Mac OS X)
  -V, --no-yield : Skip `((executable-yield-handler) <status>)' on exit
 Configuration options:
  -c, --no-compiled : Disable loading of compiled files
  -q, --no-init-file : Skip load of .racketrc for -i
  -z, --text-repl : Use text `read-eval-print-loop' for -i
  -I <path> : Set <init-lib> to <path> (sets language)
  -X <dir>, --collects <dir> : Main collects at <dir> (or "" disables all)
  -S <dir>, --search <dir> : More collects at <dir> (after main collects)
  -G <dir>, --config <dir> : Main configuration directory at <dir>
  -A <dir>, --addon <dir> : Addon directory at <dir>
  -U, --no-user-path : Ignore user-specific collects, etc.
  -R <paths>, --compiled <paths> : Set compiled-file search roots to <paths>
  -C, --cross : Cross-build mode; save current collects and config as host
  -N <file>, --name <file> : Sets `(find-system-path 'run-file)' to <file>
  -J <name>, ---wm-class <name> : Set WM_CLASS class to <name> (Unix)
  -j, --no-jit : No effect, since there is no just-in-time compiler
  -M, --compile-any : Compile to machine-independent form
  -d, --no-delay : Disable on-demand loading of syntax and code
  -b, --binary : No effect, since stdin and stdout/stderr are always binary
  -W <levels>, --warn <levels> : Set stderr logging to <levels>
  -O <levels>, --stdout <levels> : Set stdout logging to <levels>
  -L <levels>, --syslog <levels> : Set syslog logging to <levels>
  --compile-machine <machine> : Compile for <machine>
  --cross-compiler <machine> <plugin-dir> : Use compiler plugin for <machine>
  --cross-server <mach> <comp> <lib> : Drive cross-compiler (as only option)
 Meta options:
  -- : No argument following this switch is used as a switch
  -h, --help : Show this information and exits, ignoring other options
Default options:
 If only configuration options are provided, -i is added
 If only configuration options are before the first argument, -u is added
 If -t/-l/-p/-u appears before the first -i/-e/-f/-r, -n is added
 <init-lib> defaults to racket/gui/init
Switch syntax:
 Multiple single-letter switches can be collapsed, with arguments placed
   after the collapsed switches; the first collapsed switch cannot be --
 Example: `-ifve file expr' is the same as `-i -f file -v -e expr'
Start-up sequence:
 1. Set `current-library-collection-paths'
 2. Require `(lib "<init-lib>")' [when -i/-e/-f/-r, unless -n]
 3. Evaluate/load expressions/files in order, until first error
 4. Load ".racketrc" [when -i]
 5. Run read-eval-print loop [when -i]
 6. Run `((executable-yield-handler) <status>)' [unless -V]
```

After:
```console
$ gracket --help
gracket: [<option> ...] <argument> ...

X configuration options (must precede all other options):

  -display <display>, -geometry <geometry>, -fn <font>,
  -font <font>, -bg <color>, -background <color>, -fg <color>,
  -foreground <color>, -iconic, -name <name>, -rv, -reverse,
  +rv, -selectionTimeout <timeout>, -synchronous, -title <title>,
  -xnllanguage <language>, -xrm <file>

File and expression options:

  -e <exprs>, --eval <exprs>
     Evaluate <exprs>, print results
  -f <file>, --load <file>
     Like -e '(load "<file>")' without printing
  -t <file>, --require <file>
     Like -e '(require (file "<file>"))' [*]
  -l <path>, --lib <path>
     Like -e '(require (lib "<path>"))' [*]
  -p <package>
     Like -e '(require (planet "<package>")' [*]
  -r <file>, --script <file>
     Same as -f <file> -N <file> --
  -u <file>, --require-script <file>
     Same as -t <file> -N <file> --
  -k <n> <m> <p>
     Load executable-embedded code from offset <n> to <p>
  -Y <file> <n> <m> <p>
     Like -k <n> <m> <p>, but from <file>
  -m, --main
     Call `main' with command-line arguments, print results

 [*] Also `require's a `main' submodule, if any

Interaction options:

  -i, --repl
     Run interactive read-eval-print loop; implies -v
  -n, --no-lib
     Skip `(require (lib "<init-lib>"))' for -i/-e/-f/-r
  -v, --version
     Show version
  -K, --back
     Don't bring application to the foreground (Mac OS X)
  -V, --no-yield
     Skip `((executable-yield-handler) <status>)' on exit

Configuration options:

  -c, --no-compiled
     Disable loading of compiled files
  -q, --no-init-file
     Skip load of .racketrc for -i
  -z, --text-repl
     Use text `read-eval-print-loop' for -i
  -I <path>
     Set <init-lib> to <path> (sets language)
  -X <dir>, --collects <dir>
     Main collects at <dir> (or "" disables all)
  -S <dir>, --search <dir>
     More collects at <dir> (after main collects)
  -G <dir>, --config <dir>
     Main configuration directory at <dir>
  -A <dir>, --addon <dir>
     Addon directory at <dir>
  -U, --no-user-path
     Ignore user-specific collects, etc.
  -R <paths>, --compiled <paths>
     Set compiled-file search roots to <paths>
  -C, --cross
     Cross-build mode; save current collects and config
     as host
  -N <file>, --name <file>
     Sets `(find-system-path 'run-file)' to <file>
  -E <file>, --exec <file>
     Sets `(find-system-path 'exec-file)' to <file>
  -J <name>, ---wm-class <name>
     Set WM_CLASS class to <name> (Unix)
  -j, --no-jit
     No effect, since there is no just-in-time compiler
  -M, --compile-any
     Compile to machine-independent form
  -d, --no-delay
     Disable on-demand loading of syntax and code
  -b, --binary
     No effect, since stdin and stdout/stderr are
     always binary
  -W <levels>, --warn <levels>
     Set stderr logging to <levels>
  -O <levels>, --stdout <levels>
     Set stdout logging to <levels>
  -L <levels>, --syslog <levels>
     Set syslog logging to <levels>
  --compile-machine <machine>
     Compile for <machine>
  --cross-compiler <machine> <plugin-dir>
     Use compiler plugin for <machine>
  --cross-server <mach> <comp> <lib>
     Drive cross-compiler (as only option)

Meta options:

  --
     No argument following this switch is used as a switch
  -Z
     Ignore the argument following this switch
  -h, --help
     Show this information and exits, ignoring other options

Default options:

  * If only configuration options are provided, -i is added
  * If only configuration options are before the first
    argument, -u is added
  * If -t/-l/-p/-u appears before the first -i/-e/-f/-r,
    -n is added
  * <init-lib> defaults to racket/gui/init

Switch syntax:

  Multiple single-letter switches can be collapsed, with
  arguments placed after the collapsed switches; the first
  collapsed switch cannot be --

  For example,

      -ifve file expr

  is the same as

      -i -f file -v -e expr

Start-up sequence:

  1. Set `current-library-collection-paths'
  2. Require `(lib "<init-lib>")' [when -i/-e/-f/-r, unless -n]
  3. Evaluate/load expressions/files in order, until first error
  4. Load ".racketrc" [when -i]
  5. Run read-eval-print loop [when -i]
  6. Run `((executable-yield-handler) <status>)' [unless -V]
```

### CODE REVIEW

**Comment by mflatt** [comment]
I like this. As a small point, this seems like a good time to move away from the old-fashioned backquote...quote quotation style and use the backquote...backquote markdown style. (The quote...quote portions are meant to be shell text, so maybe those get left alone, or maybe they get wrapped with backquote...backquote.)

I wonder whether this change could be combined with an update of the help output produced by `racket/cmdline`.

**Comment by Krasjet** [comment]
Done. Here is an example output for the new `racket/cmdline` help page

```
usage: compiler [ <option> ... ] <filename>

<option> is one of

  -v, --verbose
     Compile with verbose messages
  -p, --profile
     Compile with profiling
/ -o, --optimize-1
|    Compile with optimization level 1
| --optimize-2
|    Compile with optimization level 2,
\    which includes all of level 1
* -l <lf>, --link-flags <lf>
     Add a flag <lf> for the linker
  --help, -h
     Show this help
  --
     Do not treat any remaining argument as a switch (at this level)

 *   Asterisks indicate options allowed multiple times.
 /|\ Brackets indicate mutually exclusive options.

 Multiple single-letter switches can be combined after
 one `-`. For example, `-h-` is the same as `-h --`.
```

where the example is taken from the documentation for `racket/cmdline`

```racket
#lang racket/base
(require racket/cmdline)

(define verbose-mode (make-parameter #f))
(define profiling-on (make-parameter #f))
(define optimize-level (make-parameter 0))
(define link-flags (make-parameter null))

(define file-to-compile
  (command-line
   #:program "compiler"
   #:once-each
   [("-v" "--verbose") "Compile with verbose messages"
                       (verbose-mode #t)]
   [("-p" "--profile") "Compile with profiling"
                       (profiling-on #t)]
   #:once-any
   [("-o" "--optimize-1") "Compile with optimization level 1"
                          (optimize-level 1)]
   ["--optimize-2"        ("Compile with optimization level 2,"
                           "which includes all of level 1")
                          (optimize-level 2)]
   #:multi
   [("-l" "--link-flags") lf
                          "Add a flag <lf> for the linker"
                          (link-flags (cons lf (link-flags)))]
   #:args (filename)
   filename))
```

**Comment by Krasjet** [comment]
Since `raco` sub-commands are using `racket/cmdline`, we now have better `--help` output for `raco` commands as well

```
usage: raco test [ <option> ... ] [<file-or-directory-or-collects-or-pkgs>] ...

<option> is one of

/ --collection, -c
|    Interpret arguments as collections
| --lib, -l
|    Interpret arguments as libraries
| --package, -p
|    Interpret arguments as packages
| --modules, -m
|    Interpret arguments as modules
\      (ignore argument unless ".rkt", ".scrbl", or enabled by "info.rkt")
  --drdr
     Configure defaults to imitate DrDr
* --submodule <name>, -s <name>
     Runs submodule <name>
    (defaults to running just the `test` submodule)
* ++arg <arg>
     Adds <arg> to the end of `current-command-line-arguments`
* ++args <args>
     Adds each whitespace-delimited in <args> like ++arg
/ --run-if-absent, -r
|    Require module if submodule is absent (on by default)
| --no-run-if-absent, -x
\    Require nothing if submodule is absent
  --first-avail
     Run only the first available submodule
  --configure-runtime
     Run the `configure-runtime' submodule
/ --direct
|    Run tests directly (default for a single file)
| --process
|    Run tests in separate processes (default for multiple files)
| --place
\    Run tests in places
  --jobs <n>, -j <n>
     Run up to <n> tests in parallel
  --timeout <seconds>
     Set default timeout to <seconds>
  --fresh-user
     Fresh PLTUSERHOME, etc., for each test
  --empty-stdin
     Call program with an empty stdin
  --quiet-program, -Q
     Quiet the program
  --check-stderr, -e
     Treat stderr output as a test failure
  --deps
     If treating arguments as packages, also test dependencies
* ++ignore-stderr <pattern>
     Ignore stderr output that matches #px"<pattern>"
  --quiet, -q
     Suppress `raco test: ...` message
  --heartbeat
     Periodically report that a test is still running
  --table, -t
     Print a summary table
  --output <file>, -o <file>
     Save stdout and stderr to file, overwrite if it exists.
  --help, -h
     Show this help
  --
     Do not treat any remaining argument as a switch (at this level)

 *   Asterisks indicate options allowed multiple times.
 /|\ Brackets indicate mutually exclusive options.

 Multiple single-letter switches can be combined after
 one `-`. For example, `-h-` is the same as `-h --`.
```

**Comment by mflatt** [comment]
This is great!

The one last piece is updating the Racket BC copy of the help text in "racket/src/bc/cmdline.inc". But I'm happy to merge and update BC myself, unless you'd like to update that file, too.

**Comment by Krasjet** [comment]
done. This should be ready to merge.

**Pull request merged**
