### PR TITLE
Create `racket/place/dynamic` to reduce dependencies.

### PR DESCRIPTION
**Pull request by samth**
Also adjust implementation of th-places slightly to avoid startup
time dependencies.

Still needs documentation.

### CODE REVIEW

**Comment by mflatt** [comment]
Looks good on a first glance. Is the documentation change to add `racket./place/dynamic` (i.e., no change to existing bindings or functionality)?

**Comment by samth** [comment]
Yeah, the documentation change is just to note that this module exists and that various things are provided by it.

**Comment by samth** [comment]
I've put in something for the documentation, but I'm not sure exactly what we want to say, and I've run into my usual inability to make `declare-exporting` do what I want in any non-standard case.

**Comment by samth** [comment]
@mflatt any thoughts on what I need to change about `declare-exporting` here?

**Comment by mflatt** [comment]
I did something and pushed. Feel free to adjust further, of course.

**Comment by mflatt** [comment]
Probably `private/place.rkt` should have been `place/private/dynamic.rkt`. I forgot that `place/private/` already exists.

**Comment by nwg** [comment]
@samth @mflatt I see @samth's branch is deleted, unless i'm misunderstanding. Does anyone mind if i pick this back up? I was going to use '#%racket but i realized i would kinda just be reproducing work here.

**Comment by nwg** [comment]
Thanks i'm excited about this.

**Comment by samth** [comment]
To link the strands together, this was merged in https://github.com/racket/racket/commit/117300621288e0d230c97bfa4012d1c98d09de1c

**Comment by nwg** [comment]
Ok. I tested this in my application and performance is much better. Everything seems to work fine.

**Pull request closed without merging**
