### PR TITLE
Use CPUS instead of -j on top level makefile

### PR DESCRIPTION
**Pull request by pmatos**
AFAIU -j will only work on a make file level but is not propagated to
raco.

### CODE REVIEW

**Comment by pmatos** [comment]
Pretty sure I discussed this with @mflatt awhile ago and this was the whole point of `CPUS` vs `-j`.

**Comment by pmatos** [comment]
> I think installers doesn't handle CPUS, though.

I am confused - the installers target uses other targets to build bc and cs so I would expect it to work. I see for example:
```
cpus-cs:
	$(MAKE) -j $(CPUS) plain-cs JOB_OPTIONS="-j $(CPUS)"
```

**Comment by samth** [comment]
I should somehow figure out how to check this. But you're probably right.

**Comment by mflatt** [comment]
I think `CPUS` probably does not work for `snapshot-site` and similar, even for the server-side build, because those targets go through targets like `plain-base` instead of `base`.

**Comment by pmatos** [comment]
Closing pull request since `CPUS` don't work on `snapshot-site` (see @mflatt comment).

**Pull request closed without merging**
