### PR TITLE
Minor fixes found by cppcheck

### PR DESCRIPTION
**Pull request by juanfra684**

### CODE REVIEW

**Comment by vendethiel** [comment]
minor?

**Comment by samth** [comment]
I think both of those are in never-on config options.

**Comment by juanfra684** [comment]
Yeah, probably that is the reason why nobody complained before :) .

@samth, if some of the devs have some free time, try to check the code with cppcheck. It shows a lot of warnings but I don't understand the GC code.

**Comment by mflatt** [comment]
merged - thanks!

**Pull request closed without merging**
