### PR TITLE
added access to os' rng

### PR DESCRIPTION
**Pull request by eu90h**
patch fulfilling issue #1062

### CODE REVIEW

**Comment by eu90h** [comment]
Ugh.. not sure why it's failing - give me a while.

**Comment by mflatt** [comment]
As others have said in #1062, this good addition is a good idea.

Others suggested `racket/system`, but I don't think that's the right place, because "system" in `racket/system` really refers to the `system` function. I suggest making it `racket/random`.

Various tweaks would make it easier to merge:

 * The internal modules "unix_rand.rkt" and "windows_rand.rkt" should be moved into a "private" subdirectory. Also, using a hyphen instead of an underscore in the name would be more consistent with our naming conventions.

 * My sense from the earlier discussion is that "Provides strong randomness from the underlying OS" in the docs is too strong, and it should just be "Provides randomness from the operating system".

 * Use "Unix" instead of "*NIX". I know that's less technically correct, but it's our convention for now.

 * Use `@filepath{...}` for path names.

 * Use `@racket[crypto-random-bytes]` in the note to make sure it typesets and hyperlinks right. But I think the note really belongs next to `random`, not next to `crypto-random-bytes` itself. Less importantly, please reword to avoid starting the sentence with a lowercase name.

Thanks

**Comment by jackfirth** [comment]
Rather than "strong randomness", would "cryptographically secure randomness" be preferable? The function is meant to guarantee that the numbers it produces are from a cryptographically secure pseudorandom number generator provided by the OS. That's more technically accurate and conveys why you'd want to use this over `random`.

**Comment by eu90h** [comment]
Thanks a lot Matthew, `racket/random` sounds good. I'll rewrite the docs & fix everything to align with convention (sorry, still learning the ropes!)

Additionally, I'd like to thank @jackfirth a bunch for helping me review this.

**Comment by samth** [comment]
I agree with @jackfirth -- "strong" is unclear, but in cases where the OS doesn't provide genuine randomness or a well-seeded CSPRNG, we should error rather than returning something weaker.

**Comment by eu90h** [comment]
Would a statement like, "provides randomness from the underlying OS intended for use in cryptographic applications" be ok?

This statement conveys both the source and the intent.

**Comment by rfindler** [comment]
That sounds right to me.

**Comment by eu90h** [comment]
OK. Moved the procedure to a new file `racket/random`. Added new documentation for it & margin note on `random` procedure.

**Comment by rfindler** [comment]
Looks like `math`'s `random-bits`, `random-natural`, and `random-integer` should change to either call this function or to get a similar pointer/disclaimer. @ntoronto ?

Also, I noticed this slightly sub-optimal error message:

```
> (random-integer 1 1)
random-natural: contract violation
  expected: Positive-Integer
  given: 0
> 
```

**Comment by soegaard** [comment]
2015-09-20 15:03 GMT+02:00 Robby Findler <notifications@github.com>:

> Looks like math's random-bits, random-natural, and random-integer should
> change to either call this function or to get a similar pointer/disclaimer.
> @ntoronto <https://github.com/ntoronto> ?
>

It would be a bad idea to change them - so a pointer is best.

The standard random functions generate pseudo-random numbers.
This implies that we can repeat experiments using random-seed.

    #lang racket
    (require math/base)
    (random-seed 42)
    (random-bits 10)
    (random-seed 42)
    (random-bits 10)

Output:  75 75

Note: The new random generator is slower than the standard random number
generator.
          (Not a criticism - cryptographically randomness cost more)

/Jens Axel




> Also, I noticed this slightly sub-optimal error message:
>
> > (random-integer 1 1)
> random-natural: contract violation
>   expected: Positive-Integer
>   given: 0
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/pull/1064#issuecomment-141784144>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by rfindler** [comment]
That makes a lot of sense.

Thanks,
Robby

**Comment by eu90h** [comment]
I'd _totally_ forgotten the random functions exported by `math`, apologies. 
I'll add a margin note on those as well.

**Comment by rfindler** [comment]
Some other comments:

 - please make a single commit

 - please remove changes that are only whitespace (don't change pkgs/racket-doc/scribblings/reference/subprocess.scrbl or racket/collects/racket/system.rkt at all)

- This is a better definition of `crypto-random-unix-bytes`:

```
(define (crypto-random-unix-bytes n)
  (check-urandom-exists)
  (call-with-input-file* "/dev/urandom"
    (λ (port)
      (read-bytes n port))))
```

(It won't leak ports.)

- The file `random.scrbl` isn't linked in anywhere. I guess the `racket/string` organization is the best one to follow. So you would create a new subsection of the "Random Numbers" section in `numbers.scrbl` and put the content of `random.scrbl` there. 

- Please include some examples in the docs. Use fake output, however; don't actually call the real functions during documentation building. (Maybe the resulting bytes could be `#"\0\1\1\2\3\5\b\r\25\"7Y\220\351"` ?)

**Comment by rfindler** [comment]
Also: should racket/random be provided by racket? I'd say yes, but I'm not positive that's a good idea.

**Comment by eu90h** [comment]
Sorry about all that :|

I'll fix it up, thank you.

**Comment by rfindler** [comment]
On Sunday, September 20, 2015, Stefan <notifications@github.com> wrote:

> Sorry about all that :|
>
> I'll fix it up, thank you.
>
>
>

No worries! I am thankful for your contribution. Just want to make it as
good as it can be. :)

**Comment by eu90h** [comment]
Sorry for the delay, been feeling a bit ill the past week.

Thanks @rfindler for fixing the port leaking and general tips. (Learned to squash commits - glad the git voodoo actually worked!)

I moved the documentation to a subsection below the random section, and included an example (had to do some whacky stuff to not actually eval the procedure, hopefully this was done ok.)

**Comment by mflatt** [comment]
Merged (with some small changes)

**Pull request closed without merging**
