### PR TITLE
Handle get-info errors when getting pkg content.

### PR DESCRIPTION
**Pull request by samth**
Important to recover properly from eg https://pkgs.racket-lang.org/package/formica

##### Checklist

- [x] Bugfix

### CODE REVIEW

**Comment by mflatt** [comment]
Seems ok to me.

**Comment by sorawee** [comment]
Not related to this PR per se, but would it be a good idea to relax `extract-pkg-dependencies`'s contract to allow `#f`?

**Comment by mflatt** [comment]
As the first argument to `extract-pkg-dependencies`? No objection, although I'm not sure where to draw the line on allowing arguments that represent failure for an earlier step.

**Comment by samth** [comment]
I think the specified contract should change; the implementation of `extract-pkg-dependencies` already handles `#f` which is what this PR relies on.

**Comment by sorawee** [comment]
It may also be a good idea to add an option to `get-info/full` to not raise an error but instead return `#f`? But again, that's out of scope of this PR.

The PR looks good to me too.

**Pull request merged**
