### PR TITLE
Add support for method contracts to `->2`

### PR DESCRIPTION
**Pull request by stamourv**
@rfindler, could you review?

### CODE REVIEW

**Comment by rfindler** [comment]
I see this error:

```
C:\projects\racket\racket\src\worksp\gc2>..\..\..\racketcgc -G ..\..\..\..\build\config -cu make.rkt 
C:\projects\racket\racket\collects\racket\contract\private\arr-i.rkt:10:9: module: identifier already imported from: "arrow.rkt"
  at: raise-wrong-number-of-args-error
  in: "arrow-higher-order.rkt" 
  context...:
   standard-module-name-resolver 
   standard-module-name-resolver 
   standard-module-name-resolver 
   standard-module-name-resolver 
   C:\projects\racket\racket\src\racket\gc2\xform.rkt:97:24 
   retry 
   C:\projects\racket\racket\src\racket\gc2\xform.rkt: [running body] 
   C:\projects\racket\racket\src\worksp\gc2\make.rkt:117:8 
error xforming 
  context...:
   C:\projects\racket\racket\src\worksp\gc2\make.rkt:96:0: try 
   C:\projects\racket\racket\src\worksp\gc2\make.rkt: [running body] 
Copying tree...
 
C:\projects\racket\racket\src\worksp\gc2>if errorlevel 1 exit /B 1 
NMAKE : fatal error U1077: 'C:\windows\system32\cmd.EXE' : return code '0x1'
```

**Comment by rfindler** [comment]
Are there test cases that make sure that the syntax parameter resetting works properly (i.e. functions syntactically inside methods that don't themselves turn into methods)?

**Comment by stamourv** [comment]
I see it in the CI logs, but don't see it on my end. Haven't tried a from-scratch build, though.
I'll try a from-scratch build once I'm done with the rest of the cleanup. Until then, any comments on the code changes proper?

**Comment by rfindler** [comment]
It seems good, just the other comment I made.

**Comment by stamourv** [comment]
Ah, yes I missed it.
Yes, there are tests that catch that. I'm hoping to get rid of the syntax parameter altogether, though.

**Comment by stamourv** [comment]
Merged.

**Pull request closed without merging**
