### PR TITLE
pkg-stage: ~return a list, not a set~ change contract

### LINKED ISSUE #3029: `pkg-stage` broke its own contract
in:

```
#lang racket/base
(require pkg/lib)

(define (table->desc t)
  (pkg-desc (hash-ref t 'source)
            #f 
            (hash-ref t 'name)
            (hash-ref t 'checksum)
            #f))

(pkg-stage (table->desc (get-pkg-details-from-catalogs "cover")))
```

I get the contract violation:

```
pkg-stage: broke its own contract
  promised: list?
  produced: (set '(lib "cover/tests/submods/prog.rkt") '(lib "cover/tests/basic/prog.rkt") '(lib "cover/main.rkt") '(lib "cover/tests/simple-multi/2.rkt") '(lib "cover/tests/exit.rkt") '(lib "cover/tests/basic/raise.rkt") '(lib "cover/tests/error-file.rkt") '...
  in: the range of
      (->*
       (pkg-desc?)
       (#:force-strip?
        boolean?
        #:in-place?
        boolean?
        #:namespace
        namespace?
        #:quiet?
        boolean?
        #:strip
        (or/c #f 'source 'binary 'binary-lib)
        #:use-cache?
        boolean?)
       (values
        string?
        path?
        (or/c #f string?)
        boolean?
        (listof module-path?)))
  contract from: <collects>/pkg/lib.rkt
  blaming: <collects>/pkg/lib.rkt
   (assuming the contract is correct)
  at: <collects>/pkg/lib.rkt:224.3
```

### PR DESCRIPTION
**Pull request by bennn**
Change `pkg-stage` to call a different helper function that returns a list. Fixes #3029.

This fix puts lists inside all `install-info` structs.

Another simpler fix is to call `list->set` at the end of the `pkg-stage` function.

### CODE REVIEW

**Comment by mflatt** [comment]
If I'm reading things right, `install-info-module-paths` is used in "install.rkt", in which case the `set->list` approach is probably the way to go.

**Comment by mflatt** [comment]
For that matter, `pkg-stage` is also used internally (e.g., in "archive.rkt"), and those call sites currently expect a set.

Is changing the contract a possibility here?

**Comment by bennn** [comment]
Changing the contract sounds fine --- the current one always errors.

**Comment by mflatt** [comment]
Changing the contract sounds right to me.

**Pull request merged**
