### PR TITLE
guide: more #lang margin notes

### PR DESCRIPTION
**Pull request by sorawee**
This continues #4273

### CODE REVIEW

**Comment by shhyou** [comment]
Maybe for [contracts](https://github.com/racket/racket/blob/463cf39dc66ae0701cc33d5f0a365147a6e590fd/pkgs/racket-doc/scribblings/guide/contracts.scrbl) as well?

**Comment by sorawee** [comment]
The contract section already has an explicit instruction in https://docs.racket-lang.org/guide/contract-boundaries.html

**Comment by shhyou** [comment]
The last bit (except the macros which need `(for-syntax racket/base)`) seems to be `(require racket/port)` for `port->string` in I/O patterns. <https://github.com/racket/racket/blob/463cf39dc66ae0701cc33d5f0a365147a6e590fd/pkgs/racket-doc/scribblings/guide/io.scrbl#L402-L411>

**Comment by sorawee** [comment]
Thanks!

**Pull request merged**
