### PR TITLE
Add `open-input-nowhere`

### PR DESCRIPTION
**Pull request by Mehbark**
##### Checklist

- [x] Feature
- [x] tests included
- [x] documentation

### Description of change
Adds `open-input-nowhere`, an `input-port?` analogue of `open-output-nowhere` requested in issue #4730. Basic benchmarking informed the use of `(open-input-bytes #"")` for the implementation, but I'd appreciate help getting this up to mainline standards—I'm no expert.

### CODE REVIEW

**Comment by benknoble** [comment]
> * There are a lot of whitespace cleanups in this PR that makes it hard to see what the change actually is. Can you remove those?

GitHub has a toggle to ignore whitespace changes when reviewing diffs, and git diff/log/show accept several options to ignore whitespace (such as `--ignore-space-change`/`-b`, which should be sufficient here, and `--ignore-all-space`/`-w`).

**Comment by rfindler** [comment]
> > * There are a lot of whitespace cleanups in this PR that makes it hard to see what the change actually is. Can you remove those?
> 
> GitHub has a toggle to ignore whitespace changes when reviewing diffs, and git diff/log/show accept several options to ignore whitespace (such as `--ignore-space-change`/`-b`, which should be sufficient here, and `--ignore-all-space`/`-w`).

Ah, thanks, I didn't know / had forgotten that (despite seeing this advice go by before in other PR discussions, perhaps by you? sorry!). 

Still, tho, let's not merge substantive changes together with whitespace fixes. It just makes trouble for future us.

**Comment by samth** [comment]
The port tests are here: https://github.com/racket/racket/blob/master/pkgs/racket-test-core/tests/racket/port.rktl

**Comment by rfindler** [comment]
> > Although I am puzzled as I expected to find some port tests in pkgs/racket-test/tests but I didn't so I'm unsure where the test should go.
> 
> Same here, I'll read carefully and add them where appropriate. 

Great!

> Should I squash all the commits into one when I'm done?

I think for this particular change it is best to combine them. I'm happy to do it when you're done, however; no problem. When I'm looking at old commits, I find it very helpful to see both the docs changes and the test changes right there with the change. When changes are bigger it may make sense to split things out, it is just this one seems nice and self-contained.

**Comment by Mehbark** [comment]
Tests added and passing (I added failing ones first to check that they actually run), but there's some more irrelevant whitespace changes; let me know what else is needed from my end. Thanks!

**Comment by rfindler** [comment]
Thanks, I've merged this. (I don't know how to make the changes and send them back to this pull request so I just pushed them to master directly.)

**Pull request closed without merging**
