### PR TITLE
url-strings: Separate URL parsing from URL actions

### PR DESCRIPTION
**Pull request by tim-brown**
`net/url` provides functions for both converting strings
and paths to and from URLs.

`net/url` also includes functions for creating (pure and import)
network ports. This functionality `require` the HTTP client stack
which is unnecessary when URLs simple need parsing for their
"bits".

New library: `net/url-strings` handles `url->string` and `string->url`
(and also the related `path->url` and `url->path` functions). This is
required by net/url for compatability.

`net/url-exception.rkt` is factored out for use by both libraries.

- See also racket/net changes for T&D

### CODE REVIEW

**Comment by mflatt** [comment]
This looks great to me. Two requests:

 * I think the library name should be `net/url-string` (i.e., single case, consistent with libraries like
   `racket/string` – granting that, unfortunately, `net/url-structs` didn't follow that convention).

 * The `net/url` library should `(provide (all-from-out "url-string.rkt"))` instead of re-listing functions and
   adding an extra layer of contracts.

**Comment by tim-brown** [comment]
On 29/05/2015 21:53, Matthew Flatt wrote:
> This looks great to me. Two requests:
>
>   *
>
>     I think the library name should be |net/url-string| (i.e., single
>     case, consistent with libraries like
>     |racket/string| – granting that, unfortunately, |net/url-structs|
>     didn't follow that convention).
>
>   *
>
>     The |net/url| library should |(provide (all-from-out
>     "url-string.rkt"))| instead of re-listing functions and
>     adding an extra layer of contracts.

Does (provide (all-from-out ...)) preserves the contract provisions?
That's the reason I chose to keep the provide/contracts as they were
passed up to net/url.

Tim

---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by mflatt** [comment]
Yes, `(all-from-out)` keeps contracts.

**Comment by tim-brown** [comment]
Is this pull request waiting on me for anything?

**Comment by mflatt** [comment]
@tim-brown: Assuming we agree on the changes, did you already make a patch with the library name changed to `net/url-string` and re-exporting from `net/url` without an extra contract layer? I was hoping that you'd update the pull request with those changes (but haven't pressed or tried to do it myself, because I've been occupied over the past couple of weeks). Thanks!

**Comment by tim-brown** [comment]
I think this is ready to merge... AppVeyor is complaining about something in places -- I don’t think it’s my fault.

**Comment by samth** [comment]
Yes, that error from AppVeyor is unrelated.

**Comment by tim-brown** [comment]
again: is there anything holding this up from my end?

**Comment by stamourv** [comment]
Merged.

**Pull request closed without merging**
