### PR TITLE
Actions for Windows CI

### PR DESCRIPTION
**Pull request by pmatos**
Addings CI on Windows using Actions.

### CODE REVIEW

**Comment by pmatos** [comment]
Need to rebase this one before merging... Thanks for the `review+`.

**Comment by pmatos** [comment]
I am having some problems doing the `csbuild` on windows.

It seems that on Windows the ChezScheme checkout doesn't not do a `--recurse-submodules`.
https://github.com/LinkiTools/racket/commit/12da59fbd4358e3b8b0ea3e31d6e864e50d23997/checks?check_suite_id=336770366#step:3:6482

I attempted to pass those options to `csbuild.rkt` but was not successful. What's the correct way to build CS on Windows?

**Comment by pmatos** [comment]
To solve the above issue I used `csbuild.rkt -- --recurse-submodules --depth=1`. These were in turn passed to `git` during `clone`. @mflatt shouldn't we mention this in the `README` or automatically clone submodules?

**Comment by pmatos** [comment]
> To solve the above issue I used `csbuild.rkt -- --recurse-submodules --depth=1`. These were in turn passed to `git` during `clone`. @mflatt shouldn't we mention this in the `README` or automatically clone submodules?

I am actually a bit confused as to why a simple call of `csbuild.rkt` works on CI PR but not on CI Push.

**Comment by mflatt** [comment]
The `csbuild.rkt` script sets up submodules when `--pull` is provided, but `git clone` is run if the directory doesn't exist, even if `--pull` is not provided. It would be sensible to always include `--recurse-submodules` in that automatic `git pull`.

**Pull request merged**
