### PR TITLE
Update documentation contribution guide

### PR DESCRIPTION
**Pull request by sorawee**
CC: @samth

### CODE REVIEW

**Comment by mflatt** [comment]
Did you run `make` in `racket-build-guide` (as opposed to editing `build.md` directly)?

**Comment by sorawee** [comment]
I edited it directly. Didn't know that it can compile Scribble to Markdown!

**Comment by sorawee** [comment]
I ran it, and they are not meaningfully different. Should I update it, still?

**Comment by mflatt** [comment]
Don't `pkgs/racket-doc/scribblings/reference` and `pkgs/racket-doc/scribblings/guide` render with quotes, since they're paths?

**Comment by sorawee** [comment]
Now the Markdown file is compiled from Scribble.

**Comment by mflatt** [comment]
Thanks!

**Pull request merged**
