### PR TITLE
Add workflow for PR continuous integration

### PR DESCRIPTION
**Pull request by pmatos**
Here's a workflow for PRs - my point of view here is that this should be quick while covering most of the features we regularly use. Once commit happens, we run a normal workflow taking more variations into consideration.

If the normal workflow fails but passed this workflow, we can always revert the commit. Having a PR workflow taking a multiple of hours makes no sense. I think we should help contributors here by allowing them to use our CI by creating draft PRs (which automatically run our CI) and get a development turnaround that's as quick as possible.

### CODE REVIEW

**Comment by samth** [comment]
Could we make this complete faster by installing Racket from the ppa/the latest release and using that to build Racket3m instead of first building RacketCGC?

**Comment by pmatos** [comment]
It's slightly annoying that this workflow is not running on itself. No idea if it's all green so don't want to merge it. I will attempt to run this in my branch by changing it to be a pull workflow instead.

**Comment by pmatos** [comment]
> Could we make this complete faster by installing Racket from the ppa/the latest release and using that to build Racket3m instead of first building RacketCGC?

Good idea. I have to drop this for a couple of hours but I will try to see how much faster we can get by grabbing racket from ppa.

**Comment by samth** [comment]
I think we should run RacketCS tests as well on PRs, at least on one platform.

**Comment by pmatos** [comment]
> Could we make this complete faster by installing Racket from the ppa/the latest release and using that to build Racket3m instead of first building RacketCGC?

Oh - before I go... isn't it true that RacketCS sometimes need a pretty recent racket to compile and grabbing the latest stable from ppa might not work? I remember this used to be the case - maybe not anymore.

**Comment by samth** [comment]
Yes, RacketCS needs the latest Racket, so we would want to build it after building Racket3m (in parallel with testing Racket3m maybe for fastest turnaround).

**Comment by mflatt** [comment]
Racket3m may need the latest development Racket instead of the latest release, too.

**Comment by pmatos** [comment]
> Racket3m may need the latest development Racket instead of the latest release, too.

In that case, it doesn't make sense to use a pre-built racket binary if I am thinking this through. I will just get the Windows build fixed for now.

**Comment by samth** [comment]
@mflatt, when was the last time that happened?

**Comment by mflatt** [comment]
@samth The last time that "collects/compiler/private/xform.rkt" changed, probably, which was September 30.

**Comment by samth** [comment]
I guess we could distinguish two situations -- when `xform` changes and we need to use the up-to-date version (happens pretty often), and when there's a bug in `racketcgc` that causes xform not to work and thus we need the up-to-date `racketcgc`. In the latter case, we really need the latest Racket from source, in the former case we could just use the old Racket to run the new xform.

However, it's probably not worth it to figure out how to use new-xform with existing-racket just for this use case.

**Comment by pmatos** [comment]
@samth This workflow has passed: https://github.com/LinkiTools/racket/runs/314844108
Shall we get this upstream and think about optimizations later? I am worried about flaky tests but if we find them, we remove them from the workflow and open a bug to fix them.

**Comment by pmatos** [comment]
I can see that the `CI Pull Request` workflow from this PR, is being triggered on itself: Good.

**Pull request merged**
