### PR TITLE
clarify error message for take and drop

### PR DESCRIPTION
**Pull request by bennn**
#1556

@hashimmm what do you think?

### CODE REVIEW

**Comment by hashimmm** [comment]
Nice, works for me. I suppose any wording other than "chain of pairs" would be either be inaccurate or less user-friendly.

**Comment by AlexKnauth** [comment]
I don't think you need the "index reaches a non-pair" language at all. Would it make sense to replace it with something that expresses "expected a (possibly improper) list with at least ~a pairs"?

**Comment by bennn** [comment]
Okay, here's another try:
```
> (take 2 2)
; take: contract violation
;   expected: a chain of at least 2 pairs
;   given: 2
> (drop '(2) 2)
; drop: contract violation
;   expected: a list with at least 2 pairs
;   given: '(2)
```

(maybe should say "list .... elements" instead of "list .... pairs")

**Comment by bennn** [comment]
Posted one more update, based on feedback from alex

**Comment by bennn** [comment]
ping @hashimmm  @AlexKnauth , okay if I merge this tonight?

**Comment by AlexKnauth** [comment]
This looks much clearer

**Pull request merged**
