### PR TITLE
using category symbols not listed behaviour

### PR DESCRIPTION
**Pull request by spdegabrielle**
Documenting behaviour when library uses a category symbol that is not listed.

### CODE REVIEW

**Comment by sorawee** [comment]
Could you modify `@history` below to say that `'drracket-plugin` was added on 8.9.x.x?

**Comment by spdegabrielle** [comment]
> Could you modify `@history` below to say that `'drracket-plugin` was added on 8.9.x.x? (this should have been a part of #4687 -- I just realized it)

PR created: https://github.com/racket/racket/pull/4705

**Comment by sorawee** [comment]
Sorry, I didn't mean that. In the file `pkgs/racket-doc/scribblings/raco/setup.scrbl` on line 652, there was:

```
@history[#:changed "6.4" @elem{Allow a category to be a string
                               instead of a symbol.}]}
```

I propose that we changed that to:

```
@history[#:changed "6.4" @elem{Allow a category to be a string
                               instead of a symbol.}
         #:changed "8.9.0.6" @elem{Add a new category @racket['drracket-plugin].}]}
```

I haven't tested this though.

**Comment by spdegabrielle** [comment]
thanks done now

**Comment by spdegabrielle** [comment]
changed 8.9.x.x to 8.9.0.6

**Comment by sorawee** [comment]
FWIW, I just saw that the documentation for `'library` already mentions this information:

```
@item{@racket['library] : Documentation for libraries; this
           category is the default and used for unrecognized category
symbols.}
```

I still think the placement of the information in this PR makes more sense. It's very easy to miss the information when it's in the middle of a list!

**Pull request merged**
