### PR TITLE
doc: hash doc improvement

### PR DESCRIPTION
**Pull request by sorawee**
- [x] documentation

This PR (intentionally) consists of two commits. 

- The first commit replaces the name `hash` with `hsh`, since naming an argument `hash` makes linking to the function `(hash)` failed. 
- The second commit fixes a contract and strengthen a contract to be consistent with other functions.

Before:

Screenshot 2023-08-18 at 9 31 55 AM

After:

Screenshot 2023-08-18 at 10 13 18 AM

### CODE REVIEW

**Comment by usaoc** [comment]
I think `ht` is a more commonly used name for hash tables, at least in the Racket code base.

**Review by AlexKnauth — APPROVED** [review]
Looks good to me, but worth noting that other places in the documentation, such as `hash-union` etc. further down in the same page, use `h`, `h0` etc. as argument names.

**Comment by sorawee** [comment]
I like the name `ht` better than `h`, so I changed everything to `ht` (including "further down in the same page" that @AlexKnauth mentioned).

**Comment by usaoc** [comment]
The commit message still refers to the original new name (`hsh`).

**Comment by sorawee** [comment]
Thanks for the feedback! @usaoc and @AlexKnauth

**Pull request merged**
