### PR TITLE
Detect and propagate errors from tar to result of tar-gzip.

### PR DESCRIPTION
**Pull request by tonyg**
The `pkg-index` server periodically runs a task that calls `get-pkg-content` from `pkg/lib`. The task is guarded by a semaphore and a use of `call-with-semaphore`.

The thunk passed to `call-with-semaphore` is supposed to either return or raise an error. Either way, the semaphore would then be released, and subsequent executions guarded by the same semaphore could continue.

Instead, it appeared as if the thunk was never returning. This prevented all subsequent update-checks from running until the server was restarted.

What was happening was this:

 - During updating, a call to `get-pkg-content` was made for package `racket-lang-org` hosted at `git://github.com/racket/racket-lang-org` and at revision `461e03f57bed723629273f4f3dbe9fba6dd1ca15` (though the current head of that repository, `fb310a712f96650331d86f5ba44c3b1b457693fe`, also triggers the bug)

 - `get-pkg-content` was calling `download-repo!` from `pkg/private/download`

 - `download-repo!` was calling `tar-gzip` with the results of a successful git checkout operation

 - `tar-gzip` was spawning a new thread, which called `tar->output`

 - `tar->output` was failing with the following error message:

         tar: path too long for USTAR: blog/_src/posts/2007-12-19-your-security-hole-is-my-fun-hack-or-computing-factorial-in-drscheme-with-a-click-powered-loop.md
           context...:
            /home/tonyg/src/racket/racket/collects/file/tar.rkt:46:0
            /home/tonyg/src/racket/racket/collects/racket/private/map.rkt:57:19: loop
            /home/tonyg/src/racket/racket/collects/racket/private/more-scheme.rkt:261:28
            /home/tonyg/src/racket/racket/collects/file/tar.rkt:184:16

 - Because `tar->output` was running in a separate thread, the exception was being lost.

 - The main thread that was waiting for the completion of `tar->output` ended up waiting for ever because no call to `close-output-port` was ever made by the crashed thread.

There are several issues here:

 1. Lack of any kind of error-handling for the cross-thread interaction in `tar-gzip`.
 2. Problems with very long pathnames given to `tar`.
 3. Lack of any kind of timeout in the `call-with-semaphore` thunk.

This pull request adds a `with-handlers` around the call to `tar->output` in `tar-gzip` to catch any exception; if an exception is caught by the new `with-handlers`, it is re-raised in the main thread. This allows the thunk given to `call-with-semaphore` to proceed, which in turn allows subsequent updates to run.

### CODE REVIEW

**Comment by rfindler** [comment]
Probably you don't want `(with-handlers [(values`, unless you're trying explicitly to handle all things that could be passed to `raise` except `#f`. I think you want to use `exn:fail?` as the predicate instead (because catching break exceptions and propagating them is strange and confusing).

**Comment by tonyg** [comment]
I would argue against `exn:fail?`, and specifically for propagating breaks, because the use of a thread is unimportant here, and any failure or interruption should be signalled on the main thread.

**Comment by rfindler** [comment]
How would a break get queue'd for this private thread?

**Comment by rfindler** [comment]
It really doesn't matter, I suppose. We can see all the code that runs on this private thread and none of it raises anything other than `exn:fail?`.

I hope you squash the commits before pushing.

**Comment by mflatt** [comment]
This looks fine to me, although it would be great to have a test in "pkgs/racket-test/tests/file".

**Comment by tonyg** [comment]
Thanks @rfindler and @mflatt for the review comments. @mflatt, I have added a test case. On the assumption that all is OK, I'll merge this now.

**Pull request merged**
