### PR TITLE
raco pkg new template updates for travis.yml

### PR DESCRIPTION
**Pull request by apg**
- Utilize RACKET_DIR for prefix to raco commands
- Add 6.2 as a build matrix option.

### CODE REVIEW

**Comment by apg** [comment]
I'm not sure why this failed. Will pull in master and try again.

**Comment by samth** [comment]
None of those failures are your fault -- the Travis ones are intermittent errors that I've seen before, and the Appveyor one is weird but not your fault.

**Comment by samth** [comment]
Also, we should probably switch to `sudo: false`, since Travis is now explicitly marking other builds as "legacy".

**Comment by apg** [comment]
Ok. I can add a sudo: false. Will add another commit.

On Thu, Jul 23, 2015 at 1:58 PM, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> Also, we should probably switch to sudo: false, since Travis is now
> explicitly marking other builds as "legacy".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/pull/981#issuecomment-124238525>.
>



-- 
http://www.apgwoz.com

**Comment by sorawee** [comment]
Thanks; the current `raco pkg new` template fixes all of these issues already, so I think we should close this PR.

**Pull request closed without merging**
