### PR TITLE
Link to the guide and reference source locations

### PR DESCRIPTION
**Pull request by hoelzro**
I had a lot of trouble figuring out how to modify the guide to fix a typo, so I figured a link in the guide itself would help others.  I added one to the reference too!

### CODE REVIEW

**Comment by samth** [comment]
@mflatt I saw your comment after merging this. I've answered this question enough times in the IRC channel that I'm inclined to deal with fixing the links when sources change, but if you have another suggestion I'm happy to change it.

**Comment by mflatt** [comment]
In the case of the self link in the Scribble docs, it has been a problem that the release gets out of sync with the development version; changing the source doesn't affect the docs that lots of people are reading.

I think that a "contribute via ..." link makes sense imposed on installation, similar to the way the Racket banner is added at http://docs.racket-lang.org, instead of having the path built into the source and rendered docs. I imagine that a JavaScript fragment could add a suitable path onto the page; the JavaScript to add the path might be updated daily by consulting pkgs.racket-lang.org. The rendered docs need to record the source of the document for use by the script; fortunately, they already do that (to support the information you see when you click on a section title).

**Comment by samth** [comment]
Are you imagining that the JS would be served from some location that gets modified daily? I bet it would be easier to just consult pkgs.racket-lang.org on every load of the page, since that information is hosted statically anyway on the server.

**Comment by mflatt** [comment]
I had in mind that pkgs.racket-lang.org doesn't currently provide a compact mapping from module names to package sources. But adding and updating that information at pkgs.racket-lang.org (and referencing it directly in the script) sounds right.

**Comment by samth** [comment]
Ah, right, because the current static table has the full data. @jeapostrophe or @tonyg, how hard would it be to serve http://pkgs.racket-lang.org/racket-doc as a JSON document with the relevant data for that pkg?

**Comment by jeapostrophe** [comment]
It already is

http://pkgs.racket-lang.org/pkg/racket-doc.json

On Tuesday, February 10, 2015, Sam Tobin-Hochstadt <notifications@github.com>
wrote:

> Ah, right, because the current static table has the full data.
> @jeapostrophe <https://github.com/jeapostrophe> or @tonyg
> <https://github.com/tonyg>, how hard would it be to serve
> http://pkgs.racket-lang.org/racket-doc as a JSON document with the
> relevant data for that pkg?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/pull/874#issuecomment-73715883>.
>


-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by samth** [comment]
Even better!

**Comment by mflatt** [comment]
@jeapostrophe: I don't think that's the format that we need. The example path you provided embeds the package name, but the initial problem is mapping a document-source module path to a package name. The catalog overall contains that information, but not in a compact and easily searchable (in JS) format.

**Comment by samth** [comment]
@jeapostrophe you need to allow cross-origin requests in order to make this work -- just adding the header `Access-Control-Allow-Origin: *` should fix it.

**Comment by samth** [comment]
@mflatt I think we can embed the pkg name in the source, unless you're worried about the pkg that provides the reference changing names?

**Comment by mflatt** [comment]
@samth: Yes, I did have in mind trying to support documents that move to different packages. Maybe it's good enough to embed the package name in rendered document, though.

**Comment by mflatt** [comment]
I've added `x-source-pkg` to Scribble's HTML rendering

**Comment by bennn** [comment]
https://github.com/racket/scribble/pull/223 is trying to solve the same problem, but embeds more than the package name. (I need to read the comments PR more carefully.)

**Pull request closed without merging**
